#pragma once
#include "CoreMinimal.h"
#include "HonourWarTypes.h"
#include "HonourWarClassProgression.generated.h"
UENUM(BlueprintType)
enum class EHonourWarClassTier : uint8
{
    Tier1=1 UMETA(DisplayName="Tier 1 - Foundation"),
    Tier2=2 UMETA(DisplayName="Tier 2 - Specialization"),
    Tier3=3 UMETA(DisplayName="Tier 3 - Advanced"),
    Tier4=4 UMETA(DisplayName="Tier 4 - Mastery"),
    Tier5=5 UMETA(DisplayName="Tier 5 - Transcendence")
};
UENUM(BlueprintType)
enum class EHonourWarFifthTierArchetype : uint8
{
    AbyssalWarlord,EternalSpellwright,CausalityMarksman,AbsoluteShadow,EternalBenediction,InfiniteQuartermaster,VerdantParagon
};
USTRUCT(BlueprintType)
struct FHonourWarFifthTierProfile
{
    GENERATED_BODY()
    UPROPERTY(EditAnywhere, BlueprintReadOnly) EHonourWarClass BaseClass=EHonourWarClass::Warrior;
    UPROPERTY(EditAnywhere, BlueprintReadOnly) EHonourWarFifthTierArchetype Archetype=EHonourWarFifthTierArchetype::AbyssalWarlord;
    UPROPERTY(EditAnywhere, BlueprintReadOnly) FString Name=TEXT("Warrior - Abyssal Warlord");
    UPROPERTY(EditAnywhere, BlueprintReadOnly) FString Title=TEXT("The Gravitational Vanguard");
    UPROPERTY(EditAnywhere, BlueprintReadOnly) FString PrimaryWeapon=TEXT("Transcendent Greatsword");
    UPROPERTY(EditAnywhere, BlueprintReadOnly) FString SecondaryWeapon=TEXT("Abyssal Shield");
};
USTRUCT(BlueprintType)
struct FHonourWarJobProfile
{
    GENERATED_BODY()
    UPROPERTY(EditAnywhere, BlueprintReadOnly) FString Id;
    UPROPERTY(EditAnywhere, BlueprintReadOnly) EHonourWarClass BaseClass=EHonourWarClass::Warrior;
    UPROPERTY(EditAnywhere, BlueprintReadOnly) EHonourWarClassTier Tier=EHonourWarClassTier::Tier1;
    UPROPERTY(EditAnywhere, BlueprintReadOnly) int32 RequiredLevel=1;
    UPROPERTY(EditAnywhere, BlueprintReadOnly) FString JobName;
    UPROPERTY(EditAnywhere, BlueprintReadOnly) FString Title;
    UPROPERTY(EditAnywhere, BlueprintReadOnly) FString Role;
    UPROPERTY(EditAnywhere, BlueprintReadOnly) FString PrimaryStat;
    UPROPERTY(EditAnywhere, BlueprintReadOnly) FString SecondaryStat;
    UPROPERTY(EditAnywhere, BlueprintReadOnly) FString StatFocus;
    UPROPERTY(EditAnywhere, BlueprintReadOnly) int32 PowerRating=100;
    UPROPERTY(EditAnywhere, BlueprintReadOnly) FString Clothing;
    UPROPERTY(EditAnywhere, BlueprintReadOnly) FString EmotionProfile;
    UPROPERTY(EditAnywhere, BlueprintReadOnly) FString SkillList;
    UPROPERTY(EditAnywhere, BlueprintReadOnly) FString SignatureWeapon;
    UPROPERTY(EditAnywhere, BlueprintReadOnly) FString Offhand;
    UPROPERTY(EditAnywhere, BlueprintReadOnly) int32 AttackRange=240;
    UPROPERTY(EditAnywhere, BlueprintReadOnly) FString WeaponFamily=TEXT("Weapon");
    UPROPERTY(EditAnywhere, BlueprintReadOnly) FString AmmoType;
    UPROPERTY(EditAnywhere, BlueprintReadOnly) int32 StatPointBudget=30;
    UPROPERTY(EditAnywhere, BlueprintReadOnly) FString StatGrowth;
};
namespace HonourWarClassProgression
{
inline int32 RequiredLevel(EHonourWarClassTier Tier){switch(Tier){case EHonourWarClassTier::Tier2:return 25;case EHonourWarClassTier::Tier3:return 50;case EHonourWarClassTier::Tier4:return 150;case EHonourWarClassTier::Tier5:return 200;default:return 1;}}
inline EHonourWarClassTier TierForLevel(int32 Level){const int32 L=FMath::Clamp(Level,1,250);if(L>=200)return EHonourWarClassTier::Tier5;if(L>=150)return EHonourWarClassTier::Tier4;if(L>=50)return EHonourWarClassTier::Tier3;if(L>=25)return EHonourWarClassTier::Tier2;return EHonourWarClassTier::Tier1;}
inline FString TierName(EHonourWarClassTier Tier){switch(Tier){case EHonourWarClassTier::Tier2:return TEXT("Specialization");case EHonourWarClassTier::Tier3:return TEXT("Advanced");case EHonourWarClassTier::Tier4:return TEXT("Mastery");case EHonourWarClassTier::Tier5:return TEXT("Transcendence");default:return TEXT("Foundation");}}
inline EHonourWarFifthTierArchetype NaturalFifthTier(EHonourWarClass ClassId){switch(ClassId){case EHonourWarClass::Mage:return EHonourWarFifthTierArchetype::EternalSpellwright;case EHonourWarClass::Archer:return EHonourWarFifthTierArchetype::CausalityMarksman;case EHonourWarClass::Thief:return EHonourWarFifthTierArchetype::AbsoluteShadow;case EHonourWarClass::Acolyte:return EHonourWarFifthTierArchetype::EternalBenediction;case EHonourWarClass::Merchant:return EHonourWarFifthTierArchetype::InfiniteQuartermaster;case EHonourWarClass::Ranger:return EHonourWarFifthTierArchetype::VerdantParagon;default:return EHonourWarFifthTierArchetype::AbyssalWarlord;}}
inline FString FifthTierName(EHonourWarClass ClassId){switch(ClassId){case EHonourWarClass::Mage:return TEXT("Mage - Eternal Spellwright");case EHonourWarClass::Archer:return TEXT("Archer - Causality Marksman");case EHonourWarClass::Thief:return TEXT("Thief - Absolute Shadow");case EHonourWarClass::Acolyte:return TEXT("Acolyte - Eternal Benediction");case EHonourWarClass::Merchant:return TEXT("Merchant - Infinite Quartermaster");case EHonourWarClass::Ranger:return TEXT("Ranger - Verdant Paragon");default:return TEXT("Warrior - Abyssal Warlord");}}
inline const TArray<FHonourWarJobProfile>& Jobs(){static const TArray<FHonourWarJobProfile> V={
        {TEXT("JOB_WARRIOR_T1"),EHonourWarClass::Warrior,EHonourWarClassTier::Tier1,1,TEXT("Swordsman"),TEXT("Ember Vanguard"),TEXT("Foundation"),TEXT("STR"),TEXT("VIT"),TEXT("STR-VIT"),118,TEXT("Foundation warrior ensemble; class-trim sash; reinforced gloves; signature footwear"),TEXT("calm / confident / observant / focused / determined / intense / fierce / surprised / resolute / pained / shaken / recovering / smiling / proud / triumphant / weary / disappointed / reflective"),TEXT("Ember Slash;Shield Bash;Guard Break;Brave Charge;Iron Resolve;War Cry;Cleave;Ember Guard"),TEXT("Swordsman Blade"),TEXT("Training Shield"),260,TEXT("Sword"),TEXT(""),41,TEXT("STR:4;AGI:1;VIT:2;INT:1;DEX:1;LUK:1")},
        {TEXT("JOB_WARRIOR_T2"),EHonourWarClass::Warrior,EHonourWarClassTier::Tier2,25,TEXT("Knight"),TEXT("Iron Oath Knight"),TEXT("Specialization"),TEXT("STR"),TEXT("VIT"),TEXT("STR-VIT"),130,TEXT("Specialization warrior ensemble; class-trim sash; reinforced gloves; signature footwear"),TEXT("calm / confident / observant / focused / determined / intense / fierce / surprised / resolute / pained / shaken / recovering / smiling / proud / triumphant / weary / disappointed / reflective"),TEXT("Oath Strike;Bulwark Wall;Shield Breaker;Knight Charge;Fortress Heart;Lion Roar;Rending Arc;Iron Halo"),TEXT("Oath Knight Sword"),TEXT("Oath Shield"),285,TEXT("Sword"),TEXT(""),75,TEXT("STR:5;AGI:1;VIT:2;INT:1;DEX:1;LUK:1")},
        {TEXT("JOB_WARRIOR_T3"),EHonourWarClass::Warrior,EHonourWarClassTier::Tier3,50,TEXT("Paladin"),TEXT("Dawnsteel Paladin"),TEXT("Advanced"),TEXT("STR"),TEXT("VIT"),TEXT("STR-VIT"),142,TEXT("Advanced warrior ensemble; class-trim sash; reinforced gloves; signature footwear"),TEXT("calm / confident / observant / focused / determined / intense / fierce / surprised / resolute / pained / shaken / recovering / smiling / proud / triumphant / weary / disappointed / reflective"),TEXT("Dawn Verdict;Aegis Crash;Holy Brand;Crusader Rush;Radiant Guard;Judgement Field;Meteor Break;Paladin Vow"),TEXT("Dawnsteel Sword"),TEXT("Dawn Aegis"),310,TEXT("Sword"),TEXT(""),110,TEXT("STR:6;AGI:2;VIT:3;INT:2;DEX:2;LUK:2")},
        {TEXT("JOB_WARRIOR_T4"),EHonourWarClass::Warrior,EHonourWarClassTier::Tier4,150,TEXT("Warlord"),TEXT("Battlefield Warlord"),TEXT("Mastery"),TEXT("STR"),TEXT("VIT"),TEXT("STR-VIT"),154,TEXT("Mastery warrior ensemble; class-trim sash; reinforced gloves; signature footwear"),TEXT("calm / confident / observant / focused / determined / intense / fierce / surprised / resolute / pained / shaken / recovering / smiling / proud / triumphant / weary / disappointed / reflective"),TEXT("Warlord Cleave;Banner of Ruin;Titan Guard;Earthshaker;Blood Oath;War March;Gravity Crush;Battlefield Dominion"),TEXT("Warlord Greatblade"),TEXT("Warlord Shield"),335,TEXT("Sword"),TEXT(""),220,TEXT("STR:7;AGI:2;VIT:3;INT:2;DEX:2;LUK:2")},
        {TEXT("JOB_WARRIOR_T5"),EHonourWarClass::Warrior,EHonourWarClassTier::Tier5,200,TEXT("Abyssal Warlord"),TEXT("The Gravitational Vanguard"),TEXT("Transcendence"),TEXT("STR"),TEXT("VIT"),TEXT("STR-VIT"),166,TEXT("Transcendence warrior ensemble; class-trim sash; reinforced gloves; signature footwear"),TEXT("calm / confident / observant / focused / determined / intense / fierce / surprised / resolute / pained / shaken / recovering / smiling / proud / triumphant / weary / disappointed / reflective"),TEXT("Abyssal Cleave;Singularity Break;Abyss Guard;Worldbreaker Charge;Gravitational Oath;Black Banner;Event Horizon;Abyssal Dominion"),TEXT("Transcendent Greatsword"),TEXT("Abyssal Shield"),360,TEXT("Sword"),TEXT(""),280,TEXT("STR:8;AGI:3;VIT:4;INT:3;DEX:3;LUK:3")},
        {TEXT("JOB_MAGE_T1"),EHonourWarClass::Mage,EHonourWarClassTier::Tier1,1,TEXT("Novice Mage"),TEXT("Azure Apprentice"),TEXT("Foundation"),TEXT("INT"),TEXT("DEX"),TEXT("INT-DEX"),118,TEXT("Foundation mage ensemble; class-trim sash; reinforced gloves; signature footwear"),TEXT("calm / confident / observant / focused / determined / intense / fierce / surprised / resolute / pained / shaken / recovering / smiling / proud / triumphant / weary / disappointed / reflective"),TEXT("Arcane Bolt;Frost Nova;Spark Chain;Mana Shield;Flame Sigil;Blink;Rune Burst;Arcane Veil"),TEXT("Rune Staff"),TEXT("Rune Focus"),780,TEXT("Staff"),TEXT(""),41,TEXT("STR:1;AGI:1;VIT:1;INT:4;DEX:2;LUK:1")},
        {TEXT("JOB_MAGE_T2"),EHonourWarClass::Mage,EHonourWarClassTier::Tier2,25,TEXT("Wizard"),TEXT("Astral Wizard"),TEXT("Specialization"),TEXT("INT"),TEXT("DEX"),TEXT("INT-DEX"),130,TEXT("Specialization mage ensemble; class-trim sash; reinforced gloves; signature footwear"),TEXT("calm / confident / observant / focused / determined / intense / fierce / surprised / resolute / pained / shaken / recovering / smiling / proud / triumphant / weary / disappointed / reflective"),TEXT("Astral Lance;Glacier Ring;Chain Lightning;Mana Prison;Meteor Fall;Time Thread;Spell Echo;Astral Barrier"),TEXT("Astral Staff"),TEXT("Astral Focus"),805,TEXT("Staff"),TEXT(""),75,TEXT("STR:1;AGI:1;VIT:1;INT:5;DEX:2;LUK:1")},
        {TEXT("JOB_MAGE_T3"),EHonourWarClass::Mage,EHonourWarClassTier::Tier3,50,TEXT("High Wizard"),TEXT("Celestial High Wizard"),TEXT("Advanced"),TEXT("INT"),TEXT("DEX"),TEXT("INT-DEX"),142,TEXT("Advanced mage ensemble; class-trim sash; reinforced gloves; signature footwear"),TEXT("calm / confident / observant / focused / determined / intense / fierce / surprised / resolute / pained / shaken / recovering / smiling / proud / triumphant / weary / disappointed / reflective"),TEXT("Celestial Ray;Frozen Crown;Thunder Spiral;Gravity Well;Meteor Rain;Chrono Bind;Astral Prison;Arcane Cataclysm"),TEXT("Celestial Staff"),TEXT("Celestial Focus"),830,TEXT("Staff"),TEXT(""),110,TEXT("STR:2;AGI:2;VIT:2;INT:6;DEX:3;LUK:2")},
        {TEXT("JOB_MAGE_T4"),EHonourWarClass::Mage,EHonourWarClassTier::Tier4,150,TEXT("Arcane Sage"),TEXT("Grand Arcane Sage"),TEXT("Mastery"),TEXT("INT"),TEXT("DEX"),TEXT("INT-DEX"),154,TEXT("Mastery mage ensemble; class-trim sash; reinforced gloves; signature footwear"),TEXT("calm / confident / observant / focused / determined / intense / fierce / surprised / resolute / pained / shaken / recovering / smiling / proud / triumphant / weary / disappointed / reflective"),TEXT("Sage Comet;Zero Field;Storm Cage;Chrono Weave;Starfall;Aether Ward;Time Fracture;Grand Spellstorm"),TEXT("Chrono Staff"),TEXT("Aether Focus"),855,TEXT("Staff"),TEXT(""),220,TEXT("STR:2;AGI:2;VIT:2;INT:7;DEX:3;LUK:2")},
        {TEXT("JOB_MAGE_T5"),EHonourWarClass::Mage,EHonourWarClassTier::Tier5,200,TEXT("Eternal Spellwright"),TEXT("The Eternal Spellwright"),TEXT("Transcendence"),TEXT("INT"),TEXT("DEX"),TEXT("INT-DEX"),166,TEXT("Transcendence mage ensemble; class-trim sash; reinforced gloves; signature footwear"),TEXT("calm / confident / observant / focused / determined / intense / fierce / surprised / resolute / pained / shaken / recovering / smiling / proud / triumphant / weary / disappointed / reflective"),TEXT("Eternal Spellstorm;Chrono Break;Axiom Collapse;Infinite Meteor;Eternal Frost;World Rune;Time Reversal;Spellwright Ascension"),TEXT("Chrono Arcane Staff"),TEXT("Aether Focus"),880,TEXT("Staff"),TEXT(""),280,TEXT("STR:3;AGI:3;VIT:3;INT:8;DEX:4;LUK:3")},
        {TEXT("JOB_ARCHER_T1"),EHonourWarClass::Archer,EHonourWarClassTier::Tier1,1,TEXT("Bowman"),TEXT("Windrunner Bowman"),TEXT("Foundation"),TEXT("DEX"),TEXT("AGI"),TEXT("DEX-AGI"),118,TEXT("Foundation archer ensemble; class-trim sash; reinforced gloves; signature footwear"),TEXT("calm / confident / observant / focused / determined / intense / fierce / surprised / resolute / pained / shaken / recovering / smiling / proud / triumphant / weary / disappointed / reflective"),TEXT("Double Shot;Focused Arrow;Falcon Mark;Windstep;Bleed Arrow;Arrow Rain;Deadeye;Windguard"),TEXT("Windrunner Bow"),TEXT("Utility Quiver"),1250,TEXT("Bow"),TEXT(""),41,TEXT("STR:1;AGI:2;VIT:1;INT:1;DEX:4;LUK:1")},
        {TEXT("JOB_ARCHER_T2"),EHonourWarClass::Archer,EHonourWarClassTier::Tier2,25,TEXT("Hunter"),TEXT("Beast Hunter"),TEXT("Specialization"),TEXT("DEX"),TEXT("AGI"),TEXT("DEX-AGI"),130,TEXT("Specialization archer ensemble; class-trim sash; reinforced gloves; signature footwear"),TEXT("calm / confident / observant / focused / determined / intense / fierce / surprised / resolute / pained / shaken / recovering / smiling / proud / triumphant / weary / disappointed / reflective"),TEXT("Triple Shot;Hunter Snare;Beast Mark;Hawk Dash;Poison Arrow;Storm Volley;Piercing Eye;Predator Sense"),TEXT("Beast Hunter Bow"),TEXT("Hunter Quiver"),1275,TEXT("Bow"),TEXT(""),75,TEXT("STR:1;AGI:2;VIT:1;INT:1;DEX:5;LUK:1")},
        {TEXT("JOB_ARCHER_T3"),EHonourWarClass::Archer,EHonourWarClassTier::Tier3,50,TEXT("Sniper"),TEXT("Star Sniper"),TEXT("Advanced"),TEXT("DEX"),TEXT("AGI"),TEXT("DEX-AGI"),142,TEXT("Advanced archer ensemble; class-trim sash; reinforced gloves; signature footwear"),TEXT("calm / confident / observant / focused / determined / intense / fierce / surprised / resolute / pained / shaken / recovering / smiling / proud / triumphant / weary / disappointed / reflective"),TEXT("Star Arrow;Sniper Focus;Falcon Barrage;Phantom Step;Rending Volley;Rain of Arrows;Horizon Aim;Astral Arrow"),TEXT("Star Sniper Bow"),TEXT("Falcon Quiver"),1300,TEXT("Bow"),TEXT(""),110,TEXT("STR:2;AGI:3;VIT:2;INT:2;DEX:6;LUK:2")},
        {TEXT("JOB_ARCHER_T4"),EHonourWarClass::Archer,EHonourWarClassTier::Tier4,150,TEXT("Deadeye"),TEXT("Horizon Deadeye"),TEXT("Mastery"),TEXT("DEX"),TEXT("AGI"),TEXT("DEX-AGI"),154,TEXT("Mastery archer ensemble; class-trim sash; reinforced gloves; signature footwear"),TEXT("calm / confident / observant / focused / determined / intense / fierce / surprised / resolute / pained / shaken / recovering / smiling / proud / triumphant / weary / disappointed / reflective"),TEXT("Deadeye Barrage;Longshot;Hawk Dominion;Wind Rift;Crimson Volley;Skyfire Rain;Perfect Aim;Horizon Break"),TEXT("Horizon Longbow"),TEXT("Deadeye Quiver"),1325,TEXT("Bow"),TEXT(""),220,TEXT("STR:2;AGI:3;VIT:2;INT:2;DEX:7;LUK:2")},
        {TEXT("JOB_ARCHER_T5"),EHonourWarClass::Archer,EHonourWarClassTier::Tier5,200,TEXT("Causality Marksman"),TEXT("The Causality Marksman"),TEXT("Transcendence"),TEXT("DEX"),TEXT("AGI"),TEXT("DEX-AGI"),166,TEXT("Transcendence archer ensemble; class-trim sash; reinforced gloves; signature footwear"),TEXT("calm / confident / observant / focused / determined / intense / fierce / surprised / resolute / pained / shaken / recovering / smiling / proud / triumphant / weary / disappointed / reflective"),TEXT("Causality Arrow;Fatepiercer;World Falcon;Zero-Step Shot;Doomsday Volley;Sky Sever;Time Split Arrow;Causality Finale"),TEXT("Doomsday Longbow"),TEXT("Causality Quiver"),1350,TEXT("Bow"),TEXT(""),280,TEXT("STR:3;AGI:4;VIT:3;INT:3;DEX:8;LUK:3")},
        {TEXT("JOB_THIEF_T1"),EHonourWarClass::Thief,EHonourWarClassTier::Tier1,1,TEXT("Dagger Initiate"),TEXT("Nightblade Initiate"),TEXT("Foundation"),TEXT("AGI"),TEXT("LUK"),TEXT("AGI-LUK"),118,TEXT("Foundation thief ensemble; class-trim sash; reinforced gloves; signature footwear"),TEXT("calm / confident / observant / focused / determined / intense / fierce / surprised / resolute / pained / shaken / recovering / smiling / proud / triumphant / weary / disappointed / reflective"),TEXT("Quick Slash;Poison Edge;Backstep;Shadow Veil;Throwing Dagger;Venom Spiral;Silent Step;Cheap Shot"),TEXT("Initiate Daggers"),TEXT("Backup Blade"),260,TEXT("Dagger"),TEXT(""),41,TEXT("STR:1;AGI:4;VIT:1;INT:1;DEX:1;LUK:2")},
        {TEXT("JOB_THIEF_T2"),EHonourWarClass::Thief,EHonourWarClassTier::Tier2,25,TEXT("Assassin"),TEXT("Veil Assassin"),TEXT("Specialization"),TEXT("AGI"),TEXT("LUK"),TEXT("AGI-LUK"),130,TEXT("Specialization thief ensemble; class-trim sash; reinforced gloves; signature footwear"),TEXT("calm / confident / observant / focused / determined / intense / fierce / surprised / resolute / pained / shaken / recovering / smiling / proud / triumphant / weary / disappointed / reflective"),TEXT("Assassin Cut;Venom Kiss;Blink Step;Smoke Veil;Night Shuriken;Blood Spiral;Killing Intent;Shadow Feast"),TEXT("Veil Daggers"),TEXT("Venom Blade"),285,TEXT("Dagger"),TEXT(""),75,TEXT("STR:1;AGI:5;VIT:1;INT:1;DEX:1;LUK:2")},
        {TEXT("JOB_THIEF_T3"),EHonourWarClass::Thief,EHonourWarClassTier::Tier3,50,TEXT("Shadowlord"),TEXT("Umbral Shadowlord"),TEXT("Advanced"),TEXT("AGI"),TEXT("LUK"),TEXT("AGI-LUK"),142,TEXT("Advanced thief ensemble; class-trim sash; reinforced gloves; signature footwear"),TEXT("calm / confident / observant / focused / determined / intense / fierce / surprised / resolute / pained / shaken / recovering / smiling / proud / triumphant / weary / disappointed / reflective"),TEXT("Shadowlord Cut;Toxic Crescent;Phantom Shift;Umbral Cloak;Soul Dagger;Nightmare Spiral;Execution Mark;Void Assault"),TEXT("Shadowlord Blades"),TEXT("Shadow Offhand"),310,TEXT("Dagger"),TEXT(""),110,TEXT("STR:2;AGI:6;VIT:2;INT:2;DEX:2;LUK:3")},
        {TEXT("JOB_THIEF_T4"),EHonourWarClass::Thief,EHonourWarClassTier::Tier4,150,TEXT("Nightblade"),TEXT("Perfect Nightblade"),TEXT("Mastery"),TEXT("AGI"),TEXT("LUK"),TEXT("AGI-LUK"),154,TEXT("Mastery thief ensemble; class-trim sash; reinforced gloves; signature footwear"),TEXT("calm / confident / observant / focused / determined / intense / fierce / surprised / resolute / pained / shaken / recovering / smiling / proud / triumphant / weary / disappointed / reflective"),TEXT("Nightblade Storm;Perfect Ambush;Afterimage;Black Mist;Abyssal Poison;Silent Tempest;Death Sentence;Night Rift"),TEXT("Nightblade Blades"),TEXT("Voidstep Blade"),335,TEXT("Dagger"),TEXT(""),220,TEXT("STR:2;AGI:7;VIT:2;INT:2;DEX:2;LUK:3")},
        {TEXT("JOB_THIEF_T5"),EHonourWarClass::Thief,EHonourWarClassTier::Tier5,200,TEXT("Absolute Shadow"),TEXT("The Absolute Shadow"),TEXT("Transcendence"),TEXT("AGI"),TEXT("LUK"),TEXT("AGI-LUK"),166,TEXT("Transcendence thief ensemble; class-trim sash; reinforced gloves; signature footwear"),TEXT("calm / confident / observant / focused / determined / intense / fierce / surprised / resolute / pained / shaken / recovering / smiling / proud / triumphant / weary / disappointed / reflective"),TEXT("Absolute Silence;Voidstep Execution;Causality Cut;Eclipse Veil;Thousand Shade;Fate Poison;Worldshadow Rush;Absolute Shadow"),TEXT("Causality Twin Daggers"),TEXT("Voidstep Blade"),360,TEXT("Dagger"),TEXT(""),280,TEXT("STR:3;AGI:8;VIT:3;INT:3;DEX:3;LUK:4")},
        {TEXT("JOB_ACOLYTE_T1"),EHonourWarClass::Acolyte,EHonourWarClassTier::Tier1,1,TEXT("Acolyte"),TEXT("Prayer Keeper"),TEXT("Foundation"),TEXT("INT"),TEXT("VIT"),TEXT("INT-VIT"),110,TEXT("Foundation acolyte ensemble; class-trim sash; reinforced gloves; signature footwear"),TEXT("calm / confident / observant / focused / determined / intense / fierce / surprised / resolute / pained / shaken / recovering / smiling / proud / triumphant / weary / disappointed / reflective"),TEXT("Heal;Blessing;Holy Strike;Sanctuary;Light Shield;Renewal;Prayer Pulse;Holy Water"),TEXT("Prayer Mace"),TEXT("Prayer Book"),540,TEXT("Mace"),TEXT(""),41,TEXT("STR:1;AGI:1;VIT:2;INT:4;DEX:1;LUK:1")},
        {TEXT("JOB_ACOLYTE_T2"),EHonourWarClass::Acolyte,EHonourWarClassTier::Tier2,25,TEXT("Priest"),TEXT("Radiant Priest"),TEXT("Specialization"),TEXT("INT"),TEXT("VIT"),TEXT("INT-VIT"),122,TEXT("Specialization acolyte ensemble; class-trim sash; reinforced gloves; signature footwear"),TEXT("calm / confident / observant / focused / determined / intense / fierce / surprised / resolute / pained / shaken / recovering / smiling / proud / triumphant / weary / disappointed / reflective"),TEXT("Greater Heal;Agi Blessing;Holy Brand;Sanctuary Field;Divine Guard;Rebirth Prayer;Radiant Hammer;Priest's Grace"),TEXT("Radiant Mace"),TEXT("Radiant Scripture"),565,TEXT("Mace"),TEXT(""),75,TEXT("STR:1;AGI:1;VIT:2;INT:5;DEX:1;LUK:1")},
        {TEXT("JOB_ACOLYTE_T3"),EHonourWarClass::Acolyte,EHonourWarClassTier::Tier3,50,TEXT("High Priest"),TEXT("Seraph High Priest"),TEXT("Advanced"),TEXT("INT"),TEXT("VIT"),TEXT("INT-VIT"),134,TEXT("Advanced acolyte ensemble; class-trim sash; reinforced gloves; signature footwear"),TEXT("calm / confident / observant / focused / determined / intense / fierce / surprised / resolute / pained / shaken / recovering / smiling / proud / triumphant / weary / disappointed / reflective"),TEXT("Mass Heal;Blessing of Ages;Seraphic Ray;Sacred Ground;Divine Aegis;Resurrection;Holy Judgement;Heavenfall"),TEXT("Seraph Mace"),TEXT("Seraph Scripture"),590,TEXT("Mace"),TEXT(""),110,TEXT("STR:2;AGI:2;VIT:3;INT:6;DEX:2;LUK:2")},
        {TEXT("JOB_ACOLYTE_T4"),EHonourWarClass::Acolyte,EHonourWarClassTier::Tier4,150,TEXT("Saint"),TEXT("Dawn Saint"),TEXT("Mastery"),TEXT("INT"),TEXT("VIT"),TEXT("INT-VIT"),146,TEXT("Mastery acolyte ensemble; class-trim sash; reinforced gloves; signature footwear"),TEXT("calm / confident / observant / focused / determined / intense / fierce / surprised / resolute / pained / shaken / recovering / smiling / proud / triumphant / weary / disappointed / reflective"),TEXT("Eternal Grace;Saint's Barrier;Seraph Lance;Dawn Sanctuary;Miracle Pulse;Judgement Bell;Life Return;Radiant Dominion"),TEXT("Saint Mace"),TEXT("Saint Scripture"),615,TEXT("Mace"),TEXT(""),220,TEXT("STR:2;AGI:2;VIT:3;INT:7;DEX:2;LUK:2")},
        {TEXT("JOB_ACOLYTE_T5"),EHonourWarClass::Acolyte,EHonourWarClassTier::Tier5,200,TEXT("Eternal Benediction"),TEXT("The Eternal Benediction"),TEXT("Transcendence"),TEXT("INT"),TEXT("VIT"),TEXT("INT-VIT"),158,TEXT("Transcendence acolyte ensemble; class-trim sash; reinforced gloves; signature footwear"),TEXT("calm / confident / observant / focused / determined / intense / fierce / surprised / resolute / pained / shaken / recovering / smiling / proud / triumphant / weary / disappointed / reflective"),TEXT("Eternal Benediction;Chrono Sanctify;Seraphic Rebirth;World Prayer;Aegis of Eternity;Heaven's Mercy;Final Hymn;Benediction of Ages"),TEXT("Chrono Sanctified Mace"),TEXT("Seraphic Scripture"),640,TEXT("Mace"),TEXT(""),280,TEXT("STR:3;AGI:3;VIT:4;INT:8;DEX:3;LUK:3")},
        {TEXT("JOB_MERCHANT_T1"),EHonourWarClass::Merchant,EHonourWarClassTier::Tier1,1,TEXT("Merchant"),TEXT("Guild Trader"),TEXT("Foundation"),TEXT("STR"),TEXT("DEX"),TEXT("STR-DEX"),118,TEXT("Foundation merchant ensemble; class-trim sash; reinforced gloves; signature footwear"),TEXT("calm / confident / observant / focused / determined / intense / fierce / surprised / resolute / pained / shaken / recovering / smiling / proud / triumphant / weary / disappointed / reflective"),TEXT("Mammonite;Trade Insight;Forge Edge;Cart Slam;Overcharge;Discount Sense;Coin Toss;Trader's Guard"),TEXT("Trader Axe"),TEXT("Trade Ledger"),320,TEXT("Axe"),TEXT(""),41,TEXT("STR:4;AGI:1;VIT:1;INT:1;DEX:2;LUK:1")},
        {TEXT("JOB_MERCHANT_T2"),EHonourWarClass::Merchant,EHonourWarClassTier::Tier2,25,TEXT("Ironforger"),TEXT("Master Ironforger"),TEXT("Specialization"),TEXT("STR"),TEXT("DEX"),TEXT("STR-DEX"),130,TEXT("Specialization merchant ensemble; class-trim sash; reinforced gloves; signature footwear"),TEXT("calm / confident / observant / focused / determined / intense / fierce / surprised / resolute / pained / shaken / recovering / smiling / proud / triumphant / weary / disappointed / reflective"),TEXT("Royal Mammonite;Market Feint;Ironforge;Cart Cannon;Profit Surge;Appraisal;Riches Ward;Merchant's Rush"),TEXT("Ironforger Hammeraxe"),TEXT("Forge Ledger"),345,TEXT("Axe"),TEXT(""),75,TEXT("STR:5;AGI:1;VIT:1;INT:1;DEX:2;LUK:1")},
        {TEXT("JOB_MERCHANT_T3"),EHonourWarClass::Merchant,EHonourWarClassTier::Tier3,50,TEXT("Royal Smith"),TEXT("Royal Trade Artisan"),TEXT("Advanced"),TEXT("STR"),TEXT("DEX"),TEXT("STR-DEX"),142,TEXT("Advanced merchant ensemble; class-trim sash; reinforced gloves; signature footwear"),TEXT("calm / confident / observant / focused / determined / intense / fierce / surprised / resolute / pained / shaken / recovering / smiling / proud / triumphant / weary / disappointed / reflective"),TEXT("Smithing Burst;Trade Mastery;Refine Strike;Cart Avalanche;Fortune Mark;Royal Appraisal;Forgemind;Guild Hammer"),TEXT("Royal Smith Axe"),TEXT("Royal Ledger"),370,TEXT("Axe"),TEXT(""),110,TEXT("STR:6;AGI:2;VIT:2;INT:2;DEX:3;LUK:2")},
        {TEXT("JOB_MERCHANT_T4"),EHonourWarClass::Merchant,EHonourWarClassTier::Tier4,150,TEXT("Master Smith"),TEXT("Grand Master Smith"),TEXT("Mastery"),TEXT("STR"),TEXT("DEX"),TEXT("STR-DEX"),154,TEXT("Mastery merchant ensemble; class-trim sash; reinforced gloves; signature footwear"),TEXT("calm / confident / observant / focused / determined / intense / fierce / surprised / resolute / pained / shaken / recovering / smiling / proud / triumphant / weary / disappointed / reflective"),TEXT("Grand Mammonite;Forge Nova;Trade Dominion;Cart Cataclysm;Fortune Engine;Master Appraisal;Royal Workshop;Quartermaster's Call"),TEXT("Master Smith Axe"),TEXT("Master Ledger"),395,TEXT("Axe"),TEXT(""),220,TEXT("STR:7;AGI:2;VIT:2;INT:2;DEX:3;LUK:2")},
        {TEXT("JOB_MERCHANT_T5"),EHonourWarClass::Merchant,EHonourWarClassTier::Tier5,200,TEXT("Infinite Quartermaster"),TEXT("The Infinite Quartermaster"),TEXT("Transcendence"),TEXT("STR"),TEXT("DEX"),TEXT("STR-DEX"),166,TEXT("Transcendence merchant ensemble; class-trim sash; reinforced gloves; signature footwear"),TEXT("calm / confident / observant / focused / determined / intense / fierce / surprised / resolute / pained / shaken / recovering / smiling / proud / triumphant / weary / disappointed / reflective"),TEXT("Infinite Supply;Matrix Strike;World Trade;Cart Singularity;Golden Dominion;Perfect Forge;Infinite Appraisal;Quartermaster's Legacy"),TEXT("Matrix Forged Axe"),TEXT("Fabricator Ledger"),420,TEXT("Axe"),TEXT(""),280,TEXT("STR:8;AGI:3;VIT:3;INT:3;DEX:4;LUK:3")},
        {TEXT("JOB_RANGER_T1"),EHonourWarClass::Ranger,EHonourWarClassTier::Tier1,1,TEXT("Ranger"),TEXT("Trail Warden"),TEXT("Foundation"),TEXT("DEX"),TEXT("AGI"),TEXT("DEX-AGI"),118,TEXT("Foundation ranger ensemble; class-trim sash; reinforced gloves; signature footwear"),TEXT("calm / confident / observant / focused / determined / intense / fierce / surprised / resolute / pained / shaken / recovering / smiling / proud / triumphant / weary / disappointed / reflective"),TEXT("Trail Shot;Quick Bolt;Beast Call;Thorn Trap;Ranger's Mark;Bolt Volley;Wildstep;Field Dressing"),TEXT("Trail Arquebus"),TEXT("Bolt Pouch"),1450,TEXT("Fantasy Gun"),TEXT("machine_gun_bolt"),41,TEXT("STR:1;AGI:2;VIT:1;INT:1;DEX:4;LUK:1")},
        {TEXT("JOB_RANGER_T2"),EHonourWarClass::Ranger,EHonourWarClassTier::Tier2,25,TEXT("Beastmaster"),TEXT("Spirit Beastmaster"),TEXT("Specialization"),TEXT("DEX"),TEXT("AGI"),TEXT("DEX-AGI"),130,TEXT("Specialization ranger ensemble; class-trim sash; reinforced gloves; signature footwear"),TEXT("calm / confident / observant / focused / determined / intense / fierce / surprised / resolute / pained / shaken / recovering / smiling / proud / triumphant / weary / disappointed / reflective"),TEXT("Carbine Burst;Spirit Bolt;Pack Command;Bramble Snare;Hunter's Mark;Rapid Volley;Wild Dash;Beastguard"),TEXT("Spirit Carbine"),TEXT("Spirit Bolt Pouch"),1475,TEXT("Fantasy Gun"),TEXT("machine_gun_bolt"),75,TEXT("STR:1;AGI:2;VIT:1;INT:1;DEX:5;LUK:1")},
        {TEXT("JOB_RANGER_T3"),EHonourWarClass::Ranger,EHonourWarClassTier::Tier3,50,TEXT("Forest Warden"),TEXT("Grand Forest Warden"),TEXT("Advanced"),TEXT("DEX"),TEXT("AGI"),TEXT("DEX-AGI"),142,TEXT("Advanced ranger ensemble; class-trim sash; reinforced gloves; signature footwear"),TEXT("calm / confident / observant / focused / determined / intense / fierce / surprised / resolute / pained / shaken / recovering / smiling / proud / triumphant / weary / disappointed / reflective"),TEXT("Repeater Barrage;Piercing Bolt;Spirit Pack;Root Trap;Deepwood Mark;Bolt Storm;Gale Recoil;Forest Sight"),TEXT("Bramble Repeater Gun"),TEXT("Repeater Bolt Magazine"),1500,TEXT("Bolt Machine Gun"),TEXT("machine_gun_bolt"),110,TEXT("STR:2;AGI:3;VIT:2;INT:2;DEX:6;LUK:2")},
        {TEXT("JOB_RANGER_T4"),EHonourWarClass::Ranger,EHonourWarClassTier::Tier4,150,TEXT("Wild Sovereign"),TEXT("Wildheart Sovereign"),TEXT("Mastery"),TEXT("DEX"),TEXT("AGI"),TEXT("DEX-AGI"),154,TEXT("Mastery ranger ensemble; class-trim sash; reinforced gloves; signature footwear"),TEXT("calm / confident / observant / focused / determined / intense / fierce / surprised / resolute / pained / shaken / recovering / smiling / proud / triumphant / weary / disappointed / reflective"),TEXT("Bolt Machine Burst;Machine Volley;Wild Sovereign Mark;Thornline Trap;Verdant Overwatch;Rapid Repeater;Briarstep;Wildheart Barrage"),TEXT("Wildheart Bolt Machine Gun"),TEXT("Machine Gun Bolt Magazine"),1525,TEXT("Bolt Machine Gun"),TEXT("machine_gun_bolt"),220,TEXT("STR:2;AGI:3;VIT:2;INT:2;DEX:7;LUK:2")},
        {TEXT("JOB_RANGER_T5"),EHonourWarClass::Ranger,EHonourWarClassTier::Tier5,200,TEXT("Verdant Paragon"),TEXT("The Verdant Paragon"),TEXT("Transcendence"),TEXT("DEX"),TEXT("AGI"),TEXT("DEX-AGI"),166,TEXT("Transcendence ranger ensemble; class-trim sash; reinforced gloves; signature footwear"),TEXT("calm / confident / observant / focused / determined / intense / fierce / surprised / resolute / pained / shaken / recovering / smiling / proud / triumphant / weary / disappointed / reflective"),TEXT("Verdant Paragon Gun;Worldroot Volley;Machine Gun Boltstorm;Paragon Mark;Ancient Root Trap;Forest Overwatch;Fate Repeater;Verdant Finale"),TEXT("Verdant Paragon Bolt Gun"),TEXT("Verdant Machine Bolt Magazine"),1550,TEXT("Bolt Machine Gun"),TEXT("machine_gun_bolt"),280,TEXT("STR:3;AGI:4;VIT:3;INT:3;DEX:8;LUK:3")},
};return V;}
inline const FHonourWarJobProfile& JobFor(EHonourWarClass ClassId,EHonourWarClassTier Tier){for(const FHonourWarJobProfile& P:Jobs())if(P.BaseClass==ClassId&&P.Tier==Tier)return P;return Jobs()[0];}
inline FString CurrentJobName(EHonourWarClass ClassId,int32 Level){return JobFor(ClassId,TierForLevel(Level)).JobName;}
inline FString CurrentJobId(EHonourWarClass ClassId,int32 Level){return JobFor(ClassId,TierForLevel(Level)).Id;}
inline FHonourWarFifthTierProfile FifthTierProfile(EHonourWarClass ClassId){FHonourWarFifthTierProfile P;P.BaseClass=ClassId;P.Archetype=NaturalFifthTier(ClassId);P.Name=FifthTierName(ClassId);switch(ClassId){case EHonourWarClass::Mage:P.Title=TEXT("The Eternal Spellwright");P.PrimaryWeapon=TEXT("Chrono Arcane Staff");P.SecondaryWeapon=TEXT("Aether Focus");break;case EHonourWarClass::Archer:P.Title=TEXT("The Causality Marksman");P.PrimaryWeapon=TEXT("Doomsday Longbow");P.SecondaryWeapon=TEXT("Causality Quiver");break;case EHonourWarClass::Thief:P.Title=TEXT("The Absolute Shadow");P.PrimaryWeapon=TEXT("Causality Twin Daggers");P.SecondaryWeapon=TEXT("Voidstep Blade");break;case EHonourWarClass::Acolyte:P.Title=TEXT("The Eternal Benediction");P.PrimaryWeapon=TEXT("Chrono Sanctified Mace");P.SecondaryWeapon=TEXT("Seraphic Scripture");break;case EHonourWarClass::Merchant:P.Title=TEXT("The Infinite Quartermaster");P.PrimaryWeapon=TEXT("Matrix Forged Axe");P.SecondaryWeapon=TEXT("Fabricator Ledger");break;case EHonourWarClass::Ranger:P.Title=TEXT("The Verdant Paragon");P.PrimaryWeapon=TEXT("Verdant Paragon Bolt Gun");P.SecondaryWeapon=TEXT("Verdant Machine Bolt Magazine");break;default:P.Title=TEXT("The Gravitational Vanguard");P.PrimaryWeapon=TEXT("Transcendent Greatsword");P.SecondaryWeapon=TEXT("Abyssal Shield");break;}return P;}
}
