#pragma once

#include "CoreMinimal.h"

/*
 * Canonical Honour War loot database.
 * Source: data/top_100_items_cards.csv
 * 100 equipment entries + 100 card entries.
 *
 * The runtime uses these names for monster drops rather than generic placeholder
 * loot strings. Drop rates remain data-authored and age bonuses are applied by
 * the combat/economy layer rather than baked into these base entries.
 */
namespace HonourWarLootDatabase
{
    inline const TArray<FString>& Items()
    {
        static const TArray<FString> Values={
    TEXT("Astral Edge"),
    TEXT("Sunforge Blade"),
    TEXT("Moonveil Saber"),
    TEXT("Dragonwake Greatsword"),
    TEXT("Stormcaller Spear"),
    TEXT("Verdant Halberd"),
    TEXT("Nightglass Dagger"),
    TEXT("Emberwind Bow"),
    TEXT("Starfall Staff"),
    TEXT("Runebound Tome"),
    TEXT("Aegis of Dawn"),
    TEXT("Dragonhide Cuirass"),
    TEXT("Moonlit Robe"),
    TEXT("Stormguard Plate"),
    TEXT("Verdant Mantle"),
    TEXT("Nightwarden Coat"),
    TEXT("Emberweave Vest"),
    TEXT("Starcaller Raiment"),
    TEXT("Ironbark Armor"),
    TEXT("Sovereign Mail"),
    TEXT("Crown of the First Light"),
    TEXT("Dragoncrest Helm"),
    TEXT("Moonshade Circlet"),
    TEXT("Stormwatch Helm"),
    TEXT("Verdant Crown"),
    TEXT("Nightwarden Hood"),
    TEXT("Emberglass Circlet"),
    TEXT("Starforged Crown"),
    TEXT("Ironbark Helm"),
    TEXT("Sovereign Visor"),
    TEXT("Wings of Dawn"),
    TEXT("Dragonwing Cloak"),
    TEXT("Moonveil Cape"),
    TEXT("Stormrunner Mantle"),
    TEXT("Verdantwind Shawl"),
    TEXT("Nightfall Cloak"),
    TEXT("Embertrail Cape"),
    TEXT("Starpath Mantle"),
    TEXT("Ironbark Cape"),
    TEXT("Sovereign Mantle"),
    TEXT("Dawnstrider Greaves"),
    TEXT("Dragonstep Boots"),
    TEXT("Moonwalker Boots"),
    TEXT("Stormrunner Boots"),
    TEXT("Verdantstride Shoes"),
    TEXT("Nightstep Boots"),
    TEXT("Embermarch Boots"),
    TEXT("Starpath Greaves"),
    TEXT("Ironbark Greaves"),
    TEXT("Sovereign Sabatons"),
    TEXT("Sunheart Ring"),
    TEXT("Dragoncore Ring"),
    TEXT("Moonstone Seal"),
    TEXT("Stormeye Ring"),
    TEXT("Verdant Signet"),
    TEXT("Nightglass Ring"),
    TEXT("Emberheart Pendant"),
    TEXT("Starcall Talisman"),
    TEXT("Ironbark Charm"),
    TEXT("Sovereign Seal"),
    TEXT("Dawnpiercer"),
    TEXT("Dragonfire Greatblade"),
    TEXT("Moonshadow Katar"),
    TEXT("Stormbreak Lance"),
    TEXT("Verdant Reaper"),
    TEXT("Nightfall Kris"),
    TEXT("Emberstorm Crossbow"),
    TEXT("Starbound Grimoire"),
    TEXT("Ironroot Hammer"),
    TEXT("Sovereign Waraxe"),
    TEXT("Dawnplate Armor"),
    TEXT("Dragonlord Cuirass"),
    TEXT("Moonshadow Vestment"),
    TEXT("Stormbreaker Plate"),
    TEXT("Verdant Guardian Armor"),
    TEXT("Nightreaper Mail"),
    TEXT("Emberlord Armor"),
    TEXT("Starforged Cuirass"),
    TEXT("Ironroot Bulwark"),
    TEXT("Sovereign Aegis"),
    TEXT("Dawnwatch Crown"),
    TEXT("Dragonlord Helm"),
    TEXT("Moonshadow Hood"),
    TEXT("Stormbreaker Helm"),
    TEXT("Verdant Guardian Helm"),
    TEXT("Nightreaper Mask"),
    TEXT("Emberlord Crown"),
    TEXT("Starforged Circlet"),
    TEXT("Ironroot Crown"),
    TEXT("Sovereign Diadem"),
    TEXT("Dawnwind Cloak"),
    TEXT("Dragonlord Mantle"),
    TEXT("Moonshadow Cape"),
    TEXT("Stormbreaker Cloak"),
    TEXT("Verdant Guardian Shawl"),
    TEXT("Nightreaper Mantle"),
    TEXT("Emberlord Cape"),
    TEXT("Starforged Wings"),
    TEXT("Ironroot Mantle"),
    TEXT("Sovereign Cloak")
        };
        return Values;
    }

    inline const TArray<FString>& Cards()
    {
        static const TArray<FString> Values={
    TEXT("Dawn Wyrm Card"),
    TEXT("Dragon Emperor Card"),
    TEXT("Moon Serpent Card"),
    TEXT("Storm Titan Card"),
    TEXT("Verdant Ancient Card"),
    TEXT("Night Reaper Card"),
    TEXT("Ember Phoenix Card"),
    TEXT("Star Oracle Card"),
    TEXT("Iron Colossus Card"),
    TEXT("Sovereign Guardian Card"),
    TEXT("Bloodfang Wolf Card"),
    TEXT("Arcane Golem Card"),
    TEXT("Sky Mantis Card"),
    TEXT("Grave Knight Card"),
    TEXT("Plague Zombie Card"),
    TEXT("Forest Orc Card"),
    TEXT("Crimson Goblin Card"),
    TEXT("Ancient Druid Card"),
    TEXT("Royal Poring Card"),
    TEXT("Abyssal Dragon Card"),
    TEXT("Celestial Knight Card"),
    TEXT("Void Mage Card"),
    TEXT("Wild Falcon Card"),
    TEXT("Shadow Thief Card"),
    TEXT("Sacred Acolyte Card"),
    TEXT("Merchant Prince Card"),
    TEXT("Warrior Lord Card"),
    TEXT("Arcane Master Card"),
    TEXT("Ranger Sovereign Card"),
    TEXT("Thief King Card"),
    TEXT("Aegis Saint Card"),
    TEXT("Forge Master Card"),
    TEXT("World Tree Card"),
    TEXT("Star Dragon Card"),
    TEXT("Eternal Guardian Card"),
    TEXT("Inferno Lord Card"),
    TEXT("Glacial Queen Card"),
    TEXT("Thunder Roc Card"),
    TEXT("Ancient Kraken Card"),
    TEXT("Chronos Beast Card"),
    TEXT("Dawn Seraph Card"),
    TEXT("Dragon Tyrant Card"),
    TEXT("Moon Empress Card"),
    TEXT("Storm Leviathan Card"),
    TEXT("Verdant Treant Card"),
    TEXT("Nightmare Reaper Card"),
    TEXT("Ember Phoenix Lord Card"),
    TEXT("Star Seer Card"),
    TEXT("Iron Behemoth Card"),
    TEXT("Sovereign Paladin Card"),
    TEXT("Bloodfang Alpha Card"),
    TEXT("Arcane Titan Card"),
    TEXT("Skybreaker Mantis Card"),
    TEXT("Grave Emperor Card"),
    TEXT("Plague Lord Card"),
    TEXT("Forest Elder Card"),
    TEXT("Crimson Goblin King Card"),
    TEXT("Ancient Archdruid Card"),
    TEXT("Royal Poring King Card"),
    TEXT("Abyssal Wyrm Card"),
    TEXT("Celestial Champion Card"),
    TEXT("Void Archmage Card"),
    TEXT("Wild Falcon Lord Card"),
    TEXT("Shadow Assassin Card"),
    TEXT("Sacred High Priest Card"),
    TEXT("Merchant King Card"),
    TEXT("Warrior Emperor Card"),
    TEXT("Arcane Grandmaster Card"),
    TEXT("Ranger King Card"),
    TEXT("Thief Emperor Card"),
    TEXT("Aegis High Saint Card"),
    TEXT("Forge Grandmaster Card"),
    TEXT("World Tree Guardian Card"),
    TEXT("Starborn Dragon Card"),
    TEXT("Eternal Paladin Card"),
    TEXT("Inferno Emperor Card"),
    TEXT("Glacial Empress Card"),
    TEXT("Thunder Roc King Card"),
    TEXT("Ancient Kraken Lord Card"),
    TEXT("Chronos Dragon Card"),
    TEXT("Dawn Worldboss Card"),
    TEXT("Dragon Eternal Card"),
    TEXT("Moon World Serpent Card"),
    TEXT("Storm World Titan Card"),
    TEXT("Verdant World Ancient Card"),
    TEXT("Night Eternal Reaper Card"),
    TEXT("Ember Eternal Phoenix Card"),
    TEXT("Star Eternal Oracle Card"),
    TEXT("Iron World Colossus Card"),
    TEXT("Sovereign Eternal Guardian Card"),
    TEXT("Bloodfang World Wolf Card"),
    TEXT("Arcane World Golem Card"),
    TEXT("Sky World Mantis Card"),
    TEXT("Grave World Knight Card"),
    TEXT("Plague World Zombie Card"),
    TEXT("Forest World Orc Card"),
    TEXT("Crimson World Goblin Card"),
    TEXT("Ancient World Druid Card"),
    TEXT("Royal World Poring Card"),
    TEXT("Abyss World Dragon Card")
        };
        return Values;
    }

    inline const FString& ItemForRank(int32 Rank)
    {
        const TArray<FString>& Values=Items();
        return Values[FMath::Clamp(Rank-1,0,Values.Num()-1)];
    }

    inline const FString& CardForRank(int32 Rank)
    {
        const TArray<FString>& Values=Cards();
        return Values[FMath::Clamp(Rank-1,0,Values.Num()-1)];
    }
}
