#pragma once

#include "CoreMinimal.h"

/*
 * Canonical Honour War runtime loot database.
 * Production pool: 300 equipment entries + 76 item entries + 300 cards.
 * Refinement materials: Phracon, Emveretarcon, Oridecon, Zeny.
 * Ranger firearm ammunition: Rune Bolts (Tier 1-2) and Machine Gun Bolts (Tier 3-5).
 */
namespace HonourWarLootDatabase
{
    inline const TArray<FString>& Items()
    {
        static const TArray<FString> Values={
    TEXT("Astral Edge 1"),
    TEXT("Sunforge Cuirass 1"),
    TEXT("Moonveil Crown 1"),
    TEXT("Dragonwake Mantle 1"),
    TEXT("Stormcaller Greaves 1"),
    TEXT("Verdant Seal 1"),
    TEXT("Nightglass Edge 1"),
    TEXT("Emberwind Cuirass 1"),
    TEXT("Starfall Crown 1"),
    TEXT("Runebound Mantle 1"),
    TEXT("Dawnpiercer Greaves 1"),
    TEXT("Ironroot Seal 1"),
    TEXT("Astral Edge 1"),
    TEXT("Sunforge Cuirass 1"),
    TEXT("Moonveil Crown 1"),
    TEXT("Dragonwake Mantle 1"),
    TEXT("Stormcaller Greaves 1"),
    TEXT("Verdant Seal 1"),
    TEXT("Nightglass Edge 1"),
    TEXT("Emberwind Cuirass 1"),
    TEXT("Starfall Crown 1"),
    TEXT("Runebound Mantle 1"),
    TEXT("Dawnpiercer Greaves 1"),
    TEXT("Ironroot Seal 1"),
    TEXT("Astral Edge 1"),
    TEXT("Sunforge Cuirass 1"),
    TEXT("Moonveil Crown 1"),
    TEXT("Dragonwake Mantle 1"),
    TEXT("Stormcaller Greaves 1"),
    TEXT("Verdant Seal 1"),
    TEXT("Nightglass Edge 1"),
    TEXT("Emberwind Cuirass 1"),
    TEXT("Starfall Crown 1"),
    TEXT("Runebound Mantle 1"),
    TEXT("Dawnpiercer Greaves 1"),
    TEXT("Ironroot Seal 1"),
    TEXT("Astral Edge 1"),
    TEXT("Sunforge Cuirass 1"),
    TEXT("Moonveil Crown 1"),
    TEXT("Dragonwake Mantle 1"),
    TEXT("Stormcaller Greaves 1"),
    TEXT("Verdant Seal 1"),
    TEXT("Nightglass Edge 1"),
    TEXT("Emberwind Cuirass 1"),
    TEXT("Starfall Crown 1"),
    TEXT("Runebound Mantle 1"),
    TEXT("Dawnpiercer Greaves 1"),
    TEXT("Ironroot Seal 1"),
    TEXT("Astral Edge 2"),
    TEXT("Sunforge Cuirass 2"),
    TEXT("Moonveil Crown 2"),
    TEXT("Dragonwake Mantle 2"),
    TEXT("Stormcaller Greaves 2"),
    TEXT("Verdant Seal 2"),
    TEXT("Nightglass Edge 2"),
    TEXT("Emberwind Cuirass 2"),
    TEXT("Starfall Crown 2"),
    TEXT("Runebound Mantle 2"),
    TEXT("Dawnpiercer Greaves 2"),
    TEXT("Ironroot Seal 2"),
    TEXT("Astral Edge 2"),
    TEXT("Sunforge Cuirass 2"),
    TEXT("Moonveil Crown 2"),
    TEXT("Dragonwake Mantle 2"),
    TEXT("Stormcaller Greaves 2"),
    TEXT("Verdant Seal 2"),
    TEXT("Nightglass Edge 2"),
    TEXT("Emberwind Cuirass 2"),
    TEXT("Starfall Crown 2"),
    TEXT("Runebound Mantle 2"),
    TEXT("Dawnpiercer Greaves 2"),
    TEXT("Ironroot Seal 2"),
    TEXT("Astral Edge 2"),
    TEXT("Sunforge Cuirass 2"),
    TEXT("Moonveil Crown 2"),
    TEXT("Dragonwake Mantle 2"),
    TEXT("Stormcaller Greaves 2"),
    TEXT("Verdant Seal 2"),
    TEXT("Nightglass Edge 2"),
    TEXT("Emberwind Cuirass 2"),
    TEXT("Starfall Crown 2"),
    TEXT("Runebound Mantle 2"),
    TEXT("Dawnpiercer Greaves 2"),
    TEXT("Ironroot Seal 2"),
    TEXT("Astral Edge 2"),
    TEXT("Sunforge Cuirass 2"),
    TEXT("Moonveil Crown 2"),
    TEXT("Dragonwake Mantle 2"),
    TEXT("Stormcaller Greaves 2"),
    TEXT("Verdant Seal 2"),
    TEXT("Nightglass Edge 2"),
    TEXT("Emberwind Cuirass 2"),
    TEXT("Starfall Crown 2"),
    TEXT("Runebound Mantle 2"),
    TEXT("Dawnpiercer Greaves 2"),
    TEXT("Ironroot Seal 2"),
    TEXT("Astral Edge 3"),
    TEXT("Sunforge Cuirass 3"),
    TEXT("Moonveil Crown 3"),
    TEXT("Dragonwake Mantle 3"),
    TEXT("Stormcaller Greaves 3"),
    TEXT("Verdant Seal 3"),
    TEXT("Nightglass Edge 3"),
    TEXT("Emberwind Cuirass 3"),
    TEXT("Starfall Crown 3"),
    TEXT("Runebound Mantle 3"),
    TEXT("Dawnpiercer Greaves 3"),
    TEXT("Ironroot Seal 3"),
    TEXT("Astral Edge 3"),
    TEXT("Sunforge Cuirass 3"),
    TEXT("Moonveil Crown 3"),
    TEXT("Dragonwake Mantle 3"),
    TEXT("Stormcaller Greaves 3"),
    TEXT("Verdant Seal 3"),
    TEXT("Nightglass Edge 3"),
    TEXT("Emberwind Cuirass 3"),
    TEXT("Starfall Crown 3"),
    TEXT("Runebound Mantle 3"),
    TEXT("Dawnpiercer Greaves 3"),
    TEXT("Ironroot Seal 3"),
    TEXT("Astral Edge 3"),
    TEXT("Sunforge Cuirass 3"),
    TEXT("Moonveil Crown 3"),
    TEXT("Dragonwake Mantle 3"),
    TEXT("Stormcaller Greaves 3"),
    TEXT("Verdant Seal 3"),
    TEXT("Nightglass Edge 3"),
    TEXT("Emberwind Cuirass 3"),
    TEXT("Starfall Crown 3"),
    TEXT("Runebound Mantle 3"),
    TEXT("Dawnpiercer Greaves 3"),
    TEXT("Ironroot Seal 3"),
    TEXT("Astral Edge 3"),
    TEXT("Sunforge Cuirass 3"),
    TEXT("Moonveil Crown 3"),
    TEXT("Dragonwake Mantle 3"),
    TEXT("Stormcaller Greaves 3"),
    TEXT("Verdant Seal 3"),
    TEXT("Nightglass Edge 3"),
    TEXT("Emberwind Cuirass 3"),
    TEXT("Starfall Crown 3"),
    TEXT("Runebound Mantle 3"),
    TEXT("Dawnpiercer Greaves 3"),
    TEXT("Ironroot Seal 3"),
    TEXT("Astral Edge 4"),
    TEXT("Sunforge Cuirass 4"),
    TEXT("Moonveil Crown 4"),
    TEXT("Dragonwake Mantle 4"),
    TEXT("Stormcaller Greaves 4"),
    TEXT("Verdant Seal 4"),
    TEXT("Nightglass Edge 4"),
    TEXT("Emberwind Cuirass 4"),
    TEXT("Starfall Crown 4"),
    TEXT("Runebound Mantle 4"),
    TEXT("Dawnpiercer Greaves 4"),
    TEXT("Ironroot Seal 4"),
    TEXT("Astral Edge 4"),
    TEXT("Sunforge Cuirass 4"),
    TEXT("Moonveil Crown 4"),
    TEXT("Dragonwake Mantle 4"),
    TEXT("Stormcaller Greaves 4"),
    TEXT("Verdant Seal 4"),
    TEXT("Nightglass Edge 4"),
    TEXT("Emberwind Cuirass 4"),
    TEXT("Starfall Crown 4"),
    TEXT("Runebound Mantle 4"),
    TEXT("Dawnpiercer Greaves 4"),
    TEXT("Ironroot Seal 4"),
    TEXT("Astral Edge 4"),
    TEXT("Sunforge Cuirass 4"),
    TEXT("Moonveil Crown 4"),
    TEXT("Dragonwake Mantle 4"),
    TEXT("Stormcaller Greaves 4"),
    TEXT("Verdant Seal 4"),
    TEXT("Nightglass Edge 4"),
    TEXT("Emberwind Cuirass 4"),
    TEXT("Starfall Crown 4"),
    TEXT("Runebound Mantle 4"),
    TEXT("Dawnpiercer Greaves 4"),
    TEXT("Ironroot Seal 4"),
    TEXT("Astral Edge 4"),
    TEXT("Sunforge Cuirass 4"),
    TEXT("Moonveil Crown 4"),
    TEXT("Dragonwake Mantle 4"),
    TEXT("Stormcaller Greaves 4"),
    TEXT("Verdant Seal 4"),
    TEXT("Nightglass Edge 4"),
    TEXT("Emberwind Cuirass 4"),
    TEXT("Starfall Crown 4"),
    TEXT("Runebound Mantle 4"),
    TEXT("Dawnpiercer Greaves 4"),
    TEXT("Ironroot Seal 4"),
    TEXT("Astral Edge 5"),
    TEXT("Sunforge Cuirass 5"),
    TEXT("Moonveil Crown 5"),
    TEXT("Dragonwake Mantle 5"),
    TEXT("Stormcaller Greaves 5"),
    TEXT("Verdant Seal 5"),
    TEXT("Nightglass Edge 5"),
    TEXT("Emberwind Cuirass 5"),
    TEXT("Starfall Crown 5"),
    TEXT("Runebound Mantle 5"),
    TEXT("Dawnpiercer Greaves 5"),
    TEXT("Ironroot Seal 5"),
    TEXT("Astral Edge 5"),
    TEXT("Sunforge Cuirass 5"),
    TEXT("Moonveil Crown 5"),
    TEXT("Dragonwake Mantle 5"),
    TEXT("Stormcaller Greaves 5"),
    TEXT("Verdant Seal 5"),
    TEXT("Nightglass Edge 5"),
    TEXT("Emberwind Cuirass 5"),
    TEXT("Starfall Crown 5"),
    TEXT("Runebound Mantle 5"),
    TEXT("Dawnpiercer Greaves 5"),
    TEXT("Ironroot Seal 5"),
    TEXT("Astral Edge 5"),
    TEXT("Sunforge Cuirass 5"),
    TEXT("Moonveil Crown 5"),
    TEXT("Dragonwake Mantle 5"),
    TEXT("Stormcaller Greaves 5"),
    TEXT("Verdant Seal 5"),
    TEXT("Nightglass Edge 5"),
    TEXT("Emberwind Cuirass 5"),
    TEXT("Starfall Crown 5"),
    TEXT("Runebound Mantle 5"),
    TEXT("Dawnpiercer Greaves 5"),
    TEXT("Ironroot Seal 5"),
    TEXT("Astral Edge 5"),
    TEXT("Sunforge Cuirass 5"),
    TEXT("Moonveil Crown 5"),
    TEXT("Dragonwake Mantle 5"),
    TEXT("Stormcaller Greaves 5"),
    TEXT("Verdant Seal 5"),
    TEXT("Nightglass Edge 5"),
    TEXT("Emberwind Cuirass 5"),
    TEXT("Starfall Crown 5"),
    TEXT("Runebound Mantle 5"),
    TEXT("Dawnpiercer Greaves 5"),
    TEXT("Transcendent Monster Suit Legacy"),
    TEXT("Ember Edge 1 Expansion 1"),
    TEXT("Astral Cuirass 1 Expansion 2"),
    TEXT("Wind Crown 1 Expansion 3"),
    TEXT("Shadow Mantle 1 Expansion 4"),
    TEXT("Sacred Greaves 1 Expansion 5"),
    TEXT("Forge Seal 1 Expansion 6"),
    TEXT("Ranger Trail Arquebus 7"),
    TEXT("Verdant Cuirass 1 Expansion 8"),
    TEXT("Ember Crown 1 Expansion 9"),
    TEXT("Astral Mantle 1 Expansion 10"),
    TEXT("Verdant Greaves 1 Expansion 11"),
    TEXT("Forge Seal 1 Expansion 12"),
    TEXT("Ember Edge 2 Expansion 1"),
    TEXT("Astral Cuirass 2 Expansion 2"),
    TEXT("Wind Crown 2 Expansion 3"),
    TEXT("Shadow Mantle 2 Expansion 4"),
    TEXT("Sacred Greaves 2 Expansion 5"),
    TEXT("Forge Seal 2 Expansion 6"),
    TEXT("Ranger Spirit Carbine 7"),
    TEXT("Verdant Cuirass 2 Expansion 8"),
    TEXT("Ember Crown 2 Expansion 9"),
    TEXT("Astral Mantle 2 Expansion 10"),
    TEXT("Verdant Greaves 2 Expansion 11"),
    TEXT("Forge Seal 2 Expansion 12"),
    TEXT("Ember Edge 3 Expansion 1"),
    TEXT("Astral Cuirass 3 Expansion 2"),
    TEXT("Wind Crown 3 Expansion 3"),
    TEXT("Shadow Mantle 3 Expansion 4"),
    TEXT("Sacred Greaves 3 Expansion 5"),
    TEXT("Forge Seal 3 Expansion 6"),
    TEXT("Ranger Repeater Bolt Gun 7"),
    TEXT("Verdant Cuirass 3 Expansion 8"),
    TEXT("Ember Crown 3 Expansion 9"),
    TEXT("Astral Mantle 3 Expansion 10"),
    TEXT("Verdant Greaves 3 Expansion 11"),
    TEXT("Forge Seal 3 Expansion 12"),
    TEXT("Ember Edge 4 Expansion 1"),
    TEXT("Astral Cuirass 4 Expansion 2"),
    TEXT("Wind Crown 4 Expansion 3"),
    TEXT("Shadow Mantle 4 Expansion 4"),
    TEXT("Sacred Greaves 4 Expansion 5"),
    TEXT("Forge Seal 4 Expansion 6"),
    TEXT("Ranger Wildheart Bolt Gun 7"),
    TEXT("Verdant Cuirass 4 Expansion 8"),
    TEXT("Ember Crown 4 Expansion 9"),
    TEXT("Astral Mantle 4 Expansion 10"),
    TEXT("Verdant Greaves 4 Expansion 11"),
    TEXT("Forge Seal 4 Expansion 12"),
    TEXT("Ember Edge 5 Expansion 1"),
    TEXT("Astral Cuirass 5 Expansion 2"),
    TEXT("Wind Crown 5 Expansion 3"),
    TEXT("Shadow Mantle 5 Expansion 4"),
    TEXT("Sacred Greaves 5 Expansion 5"),
    TEXT("Forge Seal 5 Expansion 6"),
    TEXT("Ranger Verdant Bolt Gun 7"),
    TEXT("Verdant Cuirass 5 Expansion 8"),
    TEXT("Ember Crown 5 Expansion 9"),
    TEXT("Astral Mantle 5 Expansion 10"),
    TEXT("Verdant Greaves 5 Expansion 11"),
    TEXT("Transcendent Monster Suit"),
    TEXT("Red Potion"),
    TEXT("Orange Potion"),
    TEXT("Yellow Potion"),
    TEXT("White Potion"),
    TEXT("Blue Potion"),
    TEXT("Green Potion"),
    TEXT("Awakening Tonic"),
    TEXT("Haste Elixir"),
    TEXT("Focus Elixir"),
    TEXT("Fortune Elixir"),
    TEXT("Teleport Scroll"),
    TEXT("Return Scroll"),
    TEXT("Repair Kit"),
    TEXT("Refine Safety Charm"),
    TEXT("Card Mixer Token"),
    TEXT("Town Warp Stone"),
    TEXT("Dungeon Warp Stone"),
    TEXT("Phoenix Feather"),
    TEXT("Revive Elixir"),
    TEXT("Monster Bait"),
    TEXT("Magic Essence"),
    TEXT("Archer Quiver Pack"),
    TEXT("Thief Venom Kit"),
    TEXT("Acolyte Holy Water"),
    TEXT("Merchant Voucher"),
    TEXT("Ranger Seed Pack"),
    TEXT("Small HP Potion"),
    TEXT("Medium HP Potion"),
    TEXT("Large HP Potion"),
    TEXT("Small SP Potion"),
    TEXT("Medium SP Potion"),
    TEXT("Large SP Potion"),
    TEXT("All Stat Tonic"),
    TEXT("Critical Tonic"),
    TEXT("Flee Tonic"),
    TEXT("Hit Tonic"),
    TEXT("LUK Tonic"),
    TEXT("EXP Manual"),
    TEXT("Zeny Coupon"),
    TEXT("Quest Token"),
    TEXT("Guild Token"),
    TEXT("MVP Token"),
    TEXT("Boss Bait"),
    TEXT("Dungeon Key"),
    TEXT("Ancient Key"),
    TEXT("Dragon Key"),
    TEXT("Card Dust"),
    TEXT("Card Core"),
    TEXT("Equipment Shard"),
    TEXT("Equipment Core"),
    TEXT("Refinement Catalyst"),
    TEXT("Phracon Bundle"),
    TEXT("Emveretarcon Bundle"),
    TEXT("Oridecon Bundle"),
    TEXT("Zeny Box"),
    TEXT("Mystic Herb"),
    TEXT("Azure Crystal"),
    TEXT("Crimson Crystal"),
    TEXT("Verdant Crystal"),
    TEXT("Moon Crystal"),
    TEXT("Sun Crystal"),
    TEXT("Star Crystal"),
    TEXT("Iron Crystal"),
    TEXT("Abyss Crystal"),
    TEXT("Frost Crystal"),
    TEXT("Storm Crystal"),
    TEXT("Sacred Crystal"),
    TEXT("Shadow Crystal"),
    TEXT("World Tree Sap"),
    TEXT("Dragon Scale"),
    TEXT("Kraken Ink"),
    TEXT("Titan Heart"),
    TEXT("Oracle Eye"),
    TEXT("Guardian Sigil"),
    TEXT("Machine Gun Bolts"),
    TEXT("Rune Bolts"),
        };
        return Values;
    }

    inline const FString& EquipmentForRank(int32 Rank)
    {
        const TArray<FString>& Values=Items();
        return Values[FMath::Clamp(Rank-1,0,299)];
    }

    inline const TArray<FString>& Cards()
    {
        static const TArray<FString> Values={
    TEXT("Dawn Scout Card 1"),
    TEXT("Dragon Scout Card 1"),
    TEXT("Moon Scout Card 1"),
    TEXT("Storm Scout Card 1"),
    TEXT("Verdant Scout Card 1"),
    TEXT("Night Scout Card 1"),
    TEXT("Ember Scout Card 1"),
    TEXT("Star Scout Card 1"),
    TEXT("Iron Scout Card 1"),
    TEXT("Sovereign Scout Card 1"),
    TEXT("Bloodfang Scout Card 1"),
    TEXT("Arcane Scout Card 1"),
    TEXT("Skybreaker Scout Card 1"),
    TEXT("Grave Scout Card 1"),
    TEXT("Plague Scout Card 1"),
    TEXT("Forest Scout Card 1"),
    TEXT("Crimson Scout Card 1"),
    TEXT("Ancient Scout Card 1"),
    TEXT("Royal Scout Card 1"),
    TEXT("Abyss Scout Card 1"),
    TEXT("Dawn Hunter Card 1"),
    TEXT("Dragon Hunter Card 1"),
    TEXT("Moon Hunter Card 1"),
    TEXT("Storm Hunter Card 1"),
    TEXT("Verdant Hunter Card 1"),
    TEXT("Night Hunter Card 1"),
    TEXT("Ember Hunter Card 1"),
    TEXT("Star Hunter Card 1"),
    TEXT("Iron Hunter Card 1"),
    TEXT("Sovereign Hunter Card 1"),
    TEXT("Bloodfang Hunter Card 1"),
    TEXT("Arcane Hunter Card 1"),
    TEXT("Skybreaker Hunter Card 1"),
    TEXT("Grave Hunter Card 1"),
    TEXT("Plague Hunter Card 1"),
    TEXT("Forest Hunter Card 1"),
    TEXT("Crimson Hunter Card 1"),
    TEXT("Ancient Hunter Card 1"),
    TEXT("Royal Hunter Card 1"),
    TEXT("Abyss Hunter Card 1"),
    TEXT("Dawn Alpha Card 1"),
    TEXT("Dragon Alpha Card 1"),
    TEXT("Moon Alpha Card 1"),
    TEXT("Storm Alpha Card 1"),
    TEXT("Verdant Alpha Card 1"),
    TEXT("Night Alpha Card 1"),
    TEXT("Ember Alpha Card 1"),
    TEXT("Star Alpha Card 1"),
    TEXT("Iron Alpha Card 2"),
    TEXT("Sovereign Alpha Card 2"),
    TEXT("Bloodfang Alpha Card 2"),
    TEXT("Arcane Alpha Card 2"),
    TEXT("Skybreaker Alpha Card 2"),
    TEXT("Grave Alpha Card 2"),
    TEXT("Plague Alpha Card 2"),
    TEXT("Forest Alpha Card 2"),
    TEXT("Crimson Alpha Card 2"),
    TEXT("Ancient Alpha Card 2"),
    TEXT("Royal Alpha Card 2"),
    TEXT("Abyss Alpha Card 2"),
    TEXT("Dawn Warden Card 2"),
    TEXT("Dragon Warden Card 2"),
    TEXT("Moon Warden Card 2"),
    TEXT("Storm Warden Card 2"),
    TEXT("Verdant Warden Card 2"),
    TEXT("Night Warden Card 2"),
    TEXT("Ember Warden Card 2"),
    TEXT("Star Warden Card 2"),
    TEXT("Iron Warden Card 2"),
    TEXT("Sovereign Warden Card 2"),
    TEXT("Bloodfang Warden Card 2"),
    TEXT("Arcane Warden Card 2"),
    TEXT("Skybreaker Warden Card 2"),
    TEXT("Grave Warden Card 2"),
    TEXT("Plague Warden Card 2"),
    TEXT("Forest Warden Card 2"),
    TEXT("Crimson Warden Card 2"),
    TEXT("Ancient Warden Card 2"),
    TEXT("Royal Warden Card 2"),
    TEXT("Abyss Warden Card 2"),
    TEXT("Dawn Elder Card 2"),
    TEXT("Dragon Elder Card 2"),
    TEXT("Moon Elder Card 2"),
    TEXT("Storm Elder Card 2"),
    TEXT("Verdant Elder Card 2"),
    TEXT("Night Elder Card 2"),
    TEXT("Ember Elder Card 2"),
    TEXT("Star Elder Card 2"),
    TEXT("Iron Elder Card 2"),
    TEXT("Sovereign Elder Card 2"),
    TEXT("Bloodfang Elder Card 2"),
    TEXT("Arcane Elder Card 2"),
    TEXT("Skybreaker Elder Card 2"),
    TEXT("Grave Elder Card 2"),
    TEXT("Plague Elder Card 2"),
    TEXT("Forest Elder Card 2"),
    TEXT("Crimson Elder Card 3"),
    TEXT("Ancient Elder Card 3"),
    TEXT("Royal Elder Card 3"),
    TEXT("Abyss Elder Card 3"),
    TEXT("Dawn Lord Card 3"),
    TEXT("Dragon Lord Card 3"),
    TEXT("Moon Lord Card 3"),
    TEXT("Storm Lord Card 3"),
    TEXT("Verdant Lord Card 3"),
    TEXT("Night Lord Card 3"),
    TEXT("Ember Lord Card 3"),
    TEXT("Star Lord Card 3"),
    TEXT("Iron Lord Card 3"),
    TEXT("Sovereign Lord Card 3"),
    TEXT("Bloodfang Lord Card 3"),
    TEXT("Arcane Lord Card 3"),
    TEXT("Skybreaker Lord Card 3"),
    TEXT("Grave Lord Card 3"),
    TEXT("Plague Lord Card 3"),
    TEXT("Forest Lord Card 3"),
    TEXT("Crimson Lord Card 3"),
    TEXT("Ancient Lord Card 3"),
    TEXT("Royal Lord Card 3"),
    TEXT("Abyss Lord Card 3"),
    TEXT("Dawn Tyrant Card 3"),
    TEXT("Dragon Tyrant Card 3"),
    TEXT("Moon Tyrant Card 3"),
    TEXT("Storm Tyrant Card 3"),
    TEXT("Verdant Tyrant Card 3"),
    TEXT("Night Tyrant Card 3"),
    TEXT("Ember Tyrant Card 3"),
    TEXT("Star Tyrant Card 3"),
    TEXT("Iron Tyrant Card 3"),
    TEXT("Sovereign Tyrant Card 3"),
    TEXT("Bloodfang Tyrant Card 3"),
    TEXT("Arcane Tyrant Card 3"),
    TEXT("Skybreaker Tyrant Card 3"),
    TEXT("Grave Tyrant Card 3"),
    TEXT("Plague Tyrant Card 3"),
    TEXT("Forest Tyrant Card 3"),
    TEXT("Crimson Tyrant Card 3"),
    TEXT("Ancient Tyrant Card 3"),
    TEXT("Royal Tyrant Card 3"),
    TEXT("Abyss Tyrant Card 3"),
    TEXT("Dawn Worldbreaker Card 3"),
    TEXT("Dragon Worldbreaker Card 3"),
    TEXT("Moon Worldbreaker Card 3"),
    TEXT("Storm Worldbreaker Card 3"),
    TEXT("Verdant Worldbreaker Card 4"),
    TEXT("Night Worldbreaker Card 4"),
    TEXT("Ember Worldbreaker Card 4"),
    TEXT("Star Worldbreaker Card 4"),
    TEXT("Iron Worldbreaker Card 4"),
    TEXT("Sovereign Worldbreaker Card 4"),
    TEXT("Bloodfang Worldbreaker Card 4"),
    TEXT("Arcane Worldbreaker Card 4"),
    TEXT("Skybreaker Worldbreaker Card 4"),
    TEXT("Grave Worldbreaker Card 4"),
    TEXT("Plague Worldbreaker Card 4"),
    TEXT("Forest Worldbreaker Card 4"),
    TEXT("Crimson Worldbreaker Card 4"),
    TEXT("Ancient Worldbreaker Card 4"),
    TEXT("Royal Worldbreaker Card 4"),
    TEXT("Abyss Worldbreaker Card 4"),
    TEXT("Dawn Sovereign Card 4"),
    TEXT("Dragon Sovereign Card 4"),
    TEXT("Moon Sovereign Card 4"),
    TEXT("Storm Sovereign Card 4"),
    TEXT("Verdant Sovereign Card 4"),
    TEXT("Night Sovereign Card 4"),
    TEXT("Ember Sovereign Card 4"),
    TEXT("Star Sovereign Card 4"),
    TEXT("Iron Sovereign Card 4"),
    TEXT("Sovereign Sovereign Card 4"),
    TEXT("Bloodfang Sovereign Card 4"),
    TEXT("Arcane Sovereign Card 4"),
    TEXT("Skybreaker Sovereign Card 4"),
    TEXT("Grave Sovereign Card 4"),
    TEXT("Plague Sovereign Card 4"),
    TEXT("Forest Sovereign Card 4"),
    TEXT("Crimson Sovereign Card 4"),
    TEXT("Ancient Sovereign Card 4"),
    TEXT("Royal Sovereign Card 4"),
    TEXT("Abyss Sovereign Card 4"),
    TEXT("Dawn Eternal Card 4"),
    TEXT("Dragon Eternal Card 4"),
    TEXT("Moon Eternal Card 4"),
    TEXT("Storm Eternal Card 4"),
    TEXT("Verdant Eternal Card 4"),
    TEXT("Night Eternal Card 4"),
    TEXT("Ember Eternal Card 4"),
    TEXT("Star Eternal Card 4"),
    TEXT("Iron Eternal Card 4"),
    TEXT("Sovereign Eternal Card 4"),
    TEXT("Bloodfang Eternal Card 4"),
    TEXT("Arcane Eternal Card 4"),
    TEXT("Skybreaker Eternal Card 5"),
    TEXT("Grave Eternal Card 5"),
    TEXT("Plague Eternal Card 5"),
    TEXT("Forest Eternal Card 5"),
    TEXT("Crimson Eternal Card 5"),
    TEXT("Ancient Eternal Card 5"),
    TEXT("Royal Eternal Card 5"),
    TEXT("Abyss Eternal Card 5"),
    TEXT("Dawn Overlord Card 5"),
    TEXT("Dragon Overlord Card 5"),
    TEXT("Moon Overlord Card 5"),
    TEXT("Storm Overlord Card 5"),
    TEXT("Verdant Overlord Card 5"),
    TEXT("Night Overlord Card 5"),
    TEXT("Ember Overlord Card 5"),
    TEXT("Star Overlord Card 5"),
    TEXT("Iron Overlord Card 5"),
    TEXT("Sovereign Overlord Card 5"),
    TEXT("Bloodfang Overlord Card 5"),
    TEXT("Arcane Overlord Card 5"),
    TEXT("Skybreaker Overlord Card 5"),
    TEXT("Grave Overlord Card 5"),
    TEXT("Plague Overlord Card 5"),
    TEXT("Forest Overlord Card 5"),
    TEXT("Crimson Overlord Card 5"),
    TEXT("Ancient Overlord Card 5"),
    TEXT("Royal Overlord Card 5"),
    TEXT("Abyss Overlord Card 5"),
    TEXT("Dawn Ascendant Card 5"),
    TEXT("Dragon Ascendant Card 5"),
    TEXT("Moon Ascendant Card 5"),
    TEXT("Storm Ascendant Card 5"),
    TEXT("Verdant Ascendant Card 5"),
    TEXT("Night Ascendant Card 5"),
    TEXT("Ember Ascendant Card 5"),
    TEXT("Star Ascendant Card 5"),
    TEXT("Iron Ascendant Card 5"),
    TEXT("Sovereign Ascendant Card 5"),
    TEXT("Bloodfang Ascendant Card 5"),
    TEXT("Arcane Ascendant Card 5"),
    TEXT("Skybreaker Ascendant Card 5"),
    TEXT("Grave Ascendant Card 5"),
    TEXT("Plague Ascendant Card 5"),
    TEXT("Forest Ascendant Card 5"),
    TEXT("Crimson Ascendant Card 5"),
    TEXT("Ancient Ascendant Card 5"),
    TEXT("Royal Ascendant Card 5"),
    TEXT("World Monarch Card Legacy"),
    TEXT("Warrior Dawn Hunter Card 1"),
    TEXT("Mage Iron Hunter Card 2"),
    TEXT("Archer Moon Hunter Card 3"),
    TEXT("Thief Storm Hunter Card 4"),
    TEXT("Acolyte Verdant Hunter Card 5"),
    TEXT("Merchant Royal Hunter Card 6"),
    TEXT("Ranger Dawn Hunter Card 7"),
    TEXT("Ranger Iron Hunter Card 8"),
    TEXT("Warrior Moon Hunter Card 9"),
    TEXT("Mage Storm Hunter Card 10"),
    TEXT("Ranger Verdant Hunter Card 11"),
    TEXT("Merchant Royal Hunter Card 12"),
    TEXT("Warrior Dawn Warden Card 13"),
    TEXT("Mage Iron Warden Card 14"),
    TEXT("Archer Moon Warden Card 15"),
    TEXT("Thief Storm Warden Card 16"),
    TEXT("Acolyte Verdant Warden Card 17"),
    TEXT("Merchant Royal Warden Card 18"),
    TEXT("Ranger Dawn Warden Card 19"),
    TEXT("Ranger Iron Warden Card 20"),
    TEXT("Warrior Moon Warden Card 21"),
    TEXT("Mage Storm Warden Card 22"),
    TEXT("Ranger Verdant Warden Card 23"),
    TEXT("Merchant Royal Warden Card 24"),
    TEXT("Warrior Dawn Sovereign Card 25"),
    TEXT("Mage Iron Sovereign Card 26"),
    TEXT("Archer Moon Sovereign Card 27"),
    TEXT("Thief Storm Sovereign Card 28"),
    TEXT("Acolyte Verdant Sovereign Card 29"),
    TEXT("Merchant Royal Sovereign Card 30"),
    TEXT("Ranger Dawn Sovereign Card 31"),
    TEXT("Ranger Iron Sovereign Card 32"),
    TEXT("Warrior Moon Sovereign Card 33"),
    TEXT("Mage Storm Sovereign Card 34"),
    TEXT("Ranger Verdant Sovereign Card 35"),
    TEXT("Merchant Royal Sovereign Card 36"),
    TEXT("Warrior Dawn Eternal Card 37"),
    TEXT("Mage Iron Eternal Card 38"),
    TEXT("Archer Moon Eternal Card 39"),
    TEXT("Thief Storm Eternal Card 40"),
    TEXT("Acolyte Verdant Eternal Card 41"),
    TEXT("Merchant Royal Eternal Card 42"),
    TEXT("Ranger Dawn Eternal Card 43"),
    TEXT("Ranger Iron Eternal Card 44"),
    TEXT("Warrior Moon Eternal Card 45"),
    TEXT("Mage Storm Eternal Card 46"),
    TEXT("Ranger Verdant Eternal Card 47"),
    TEXT("Merchant Royal Eternal Card 48"),
    TEXT("Warrior Dawn Ascendant Card 49"),
    TEXT("Mage Iron Ascendant Card 50"),
    TEXT("Archer Moon Ascendant Card 51"),
    TEXT("Thief Storm Ascendant Card 52"),
    TEXT("Acolyte Verdant Ascendant Card 53"),
    TEXT("Merchant Royal Ascendant Card 54"),
    TEXT("Ranger Dawn Ascendant Card 55"),
    TEXT("Ranger Iron Ascendant Card 56"),
    TEXT("Warrior Moon Ascendant Card 57"),
    TEXT("Mage Storm Ascendant Card 58"),
    TEXT("Ranger Verdant Ascendant Card 59"),
    TEXT("World Monarch Card"),
        };
        return Values;
    }

    inline const FString& ItemForRank(int32 Rank)
    {
        const TArray<FString>& Values=Items();
        return Values[FMath::Clamp(Rank-1,0,Values.Num()-1)];
    }

    inline const FString& CardForRank(int32 Rank)
    {
        const TArray<FString>& Values=Cards();
        return Values[FMath::Clamp(Rank-1,0,Values.Num()-1)];
    }
}
