class_name ItemDatabase
extends RefCounted

static func all() -> Dictionary:
	return {
		"Red Potion":{"type":"Consumable","rarity":"Common","value":25,"effect":"Heal 120 HP"},
		"Orange Potion":{"type":"Consumable","rarity":"Uncommon","value":80,"effect":"Heal 360 HP"},
		"White Potion":{"type":"Consumable","rarity":"Rare","value":180,"effect":"Heal 900 HP"},
		"Blue Potion":{"type":"Consumable","rarity":"Uncommon","value":70,"effect":"Restore 120 SP"},
		"Awakening Potion":{"type":"Consumable","rarity":"Rare","value":240,"effect":"Attack speed +20% for 60s"},
		"Concentration Potion":{"type":"Consumable","rarity":"Rare","value":260,"effect":"Accuracy +15% for 60s"},
		"Holy Water":{"type":"Consumable","rarity":"Uncommon","value":45,"effect":"Remove one curse"},
		"Elunium":{"type":"Refine","rarity":"Rare","value":600,"effect":"Armor refine material"},
		"Oridecon":{"type":"Refine","rarity":"Epic","value":1000,"effect":"Weapon refine material"},
		"Phracon":{"type":"Refine","rarity":"Common","value":100,"effect":"Refine +0 to +4"},
		"Emveretarcon":{"type":"Refine","rarity":"Uncommon","value":350,"effect":"Refine +5 to +8"},
		"Pet Refine Item":{"type":"Pet","rarity":"Rare","value":500,"effect":"Pet refinement catalyst"},
		"Pet Skill Item":{"type":"Pet","rarity":"Epic","value":900,"effect":"Unlock/upgrade pet skill"},
		"Monster Essence":{"type":"Crafting","rarity":"Common","value":30,"effect":"Crafting reagent"},
		"Beast Fang":{"type":"Crafting","rarity":"Common","value":35,"effect":"Crafting reagent"},
		"Wolf Claw":{"type":"Crafting","rarity":"Common","value":40,"effect":"Crafting reagent"},
		"Goblin Ear":{"type":"Crafting","rarity":"Common","value":40,"effect":"Crafting reagent"},
		"Orc Tusk":{"type":"Crafting","rarity":"Uncommon","value":90,"effect":"Crafting reagent"},
		"Mantis Shell":{"type":"Crafting","rarity":"Uncommon","value":110,"effect":"Crafting reagent"},
		"Skeleton Bone":{"type":"Crafting","rarity":"Common","value":50,"effect":"Crafting reagent"},
		"Zombie Heart":{"type":"Crafting","rarity":"Uncommon","value":80,"effect":"Crafting reagent"},
		"Golem Core":{"type":"Crafting","rarity":"Rare","value":260,"effect":"Crafting reagent"},
		"Druid Relic":{"type":"Crafting","rarity":"Rare","value":320,"effect":"Crafting reagent"},
		"Dragon Scale":{"type":"Crafting","rarity":"Epic","value":850,"effect":"Endgame crafting reagent"},
		"Novice Sword":{"type":"Weapon","rarity":"Common","value":120,"attack":12,"refine_cap":15},
		"Iron Longsword":{"type":"Weapon","rarity":"Uncommon","value":650,"attack":32,"refine_cap":15},
		"Knight Claymore":{"type":"Weapon","rarity":"Rare","value":2400,"attack":70,"refine_cap":15},
		"War Emperor Blade":{"type":"Weapon","rarity":"Legendary","value":15000,"attack":180,"refine_cap":15},
		"Arcane Staff":{"type":"Weapon","rarity":"Uncommon","value":700,"attack":38,"magic":42,"refine_cap":15},
		"Astral Sovereign Staff":{"type":"Weapon","rarity":"Legendary","value":16000,"attack":150,"magic":220,"refine_cap":15},
		"Hunter Bow":{"type":"Weapon","rarity":"Uncommon","value":680,"attack":35,"crit":4,"refine_cap":15},
		"Celestial Longbow":{"type":"Weapon","rarity":"Legendary","value":15500,"attack":170,"crit":15,"refine_cap":15},
		"Shadow Dagger":{"type":"Weapon","rarity":"Rare","value":2100,"attack":62,"crit":8,"refine_cap":15},
		"Eternal Assassin Blade":{"type":"Weapon","rarity":"Legendary","value":17000,"attack":195,"crit":20,"refine_cap":15},
		"Holy Mace":{"type":"Weapon","rarity":"Uncommon","value":600,"attack":30,"healing":12,"refine_cap":15},
		"Heaven Gate Mace":{"type":"Weapon","rarity":"Legendary","value":15000,"attack":145,"healing":80,"refine_cap":15},
		"Merchant Hammer":{"type":"Weapon","rarity":"Uncommon","value":620,"attack":34,"defense":8,"refine_cap":15},
		"Arsenal Overlord Hammer":{"type":"Weapon","rarity":"Legendary","value":16500,"attack":165,"defense":45,"refine_cap":15},
		"Novice Armor":{"type":"Armor","rarity":"Common","value":120,"defense":8,"refine_cap":15},
		"Iron Plate":{"type":"Armor","rarity":"Uncommon","value":700,"defense":28,"refine_cap":15},
		"Dragon Scale Armor":{"type":"Armor","rarity":"Epic","value":6000,"defense":95,"refine_cap":15},
		"War Emperor Armor":{"type":"Armor","rarity":"Legendary","value":18000,"defense":180,"refine_cap":15},
		"Ranger Mantle":{"type":"Armor","rarity":"Rare","value":2600,"defense":48,"crit":6,"refine_cap":15},
		"Shadow Cloak":{"type":"Armor","rarity":"Rare","value":2800,"defense":44,"evasion":8,"refine_cap":15},
		"Saint Vestment":{"type":"Armor","rarity":"Epic","value":5000,"defense":72,"healing":30,"refine_cap":15},
		"Forge Master Coat":{"type":"Armor","rarity":"Epic","value":5200,"defense":85,"carry":30,"refine_cap":15},
		"Ruby Ring":{"type":"Accessory","rarity":"Rare","value":1500,"hp":180,"effect":"+3% fire damage"},
		"Sapphire Ring":{"type":"Accessory","rarity":"Rare","value":1500,"sp":120,"effect":"+3% ice damage"},
		"Emerald Brooch":{"type":"Accessory","rarity":"Rare","value":1500,"crit":5,"effect":"+3% wind damage"},
		"Amethyst Charm":{"type":"Accessory","rarity":"Epic","value":2800,"magic":30,"effect":"+4% dark damage"},
		"Golden Crown":{"type":"Accessory","rarity":"Legendary","value":9000,"hp":500,"defense":25,"effect":"+5% all rewards"},
		"MVP Treasure Chest":{"type":"Chest","rarity":"MVP","value":5000,"effect":"Contains premium boss loot"},
		"Boss Soul Shard":{"type":"Crafting","rarity":"MVP","value":2500,"effect":"MVP equipment crafting"},
		"Ancient Dragon Heart":{"type":"Crafting","rarity":"MVP","value":4500,"effect":"Legendary crafting core"},
		"Moon Crystal":{"type":"Crafting","rarity":"MVP","value":3800,"effect":"Endgame enchantment material"},
		"Thanatos Fragment":{"type":"Crafting","rarity":"MVP","value":5000,"effect":"Ultimate weapon material"},
		"Abyssal Relic":{"type":"Crafting","rarity":"MVP","value":7500,"effect":"Mythic equipment material"},
		"Teleport Scroll":{"type":"Utility","rarity":"Common","value":100,"effect":"Return to safe city"},
		"Butterfly Wing":{"type":"Utility","rarity":"Common","value":80,"effect":"Return to last safe city"},
		"Magnifier":{"type":"Utility","rarity":"Common","value":40,"effect":"Identify equipment"},
		"MVP Bounty Token":{"type":"Currency","rarity":"MVP","value":1000,"effect":"Exchange for boss rewards"}
	}
