class_name ItemDatabase
extends RefCounted

static func all() -> Dictionary:
	return {
		"Red Potion":{"type":"Consumable","rarity":"Common","value":25,"effect":"Heal 120 HP"},
		"Orange Potion":{"type":"Consumable","rarity":"Uncommon","value":80,"effect":"Heal 360 HP"},
		"White Potion":{"type":"Consumable","rarity":"Rare","value":180,"effect":"Heal 900 HP"},
		"Blue Potion":{"type":"Consumable","rarity":"Uncommon","value":70,"effect":"Restore 120 SP"},
		"Awakening Potion":{"type":"Consumable","rarity":"Rare","value":240,"effect":"Attack speed +20% for 60s"},
		"Concentration Potion":{"type":"Consumable","rarity":"Rare","value":260,"effect":"Accuracy +15% for 60s"},
		"Holy Water":{"type":"Consumable","rarity":"Uncommon","value":45,"effect":"Remove one curse"},
		"Elunium":{"type":"Refine","rarity":"Rare","value":600,"effect":"Armor refine material"},
		"Oridecon":{"type":"Refine","rarity":"Epic","value":1000,"effect":"Weapon refine material"},
		"Phracon":{"type":"Refine","rarity":"Common","value":100,"effect":"Refine +0 to +4"},
		"Emveretarcon":{"type":"Refine","rarity":"Uncommon","value":350,"effect":"Refine +5 to +8"},
		"Pet Refine Item":{"type":"Pet","rarity":"Rare","value":500,"effect":"Pet refinement catalyst"},
		"Pet Skill Item":{"type":"Pet","rarity":"Epic","value":900,"effect":"Unlock/upgrade pet skill"},
		"Monster Essence":{"type":"Crafting","rarity":"Common","value":30,"effect":"Universal monster crafting reagent"},
		"Beast Fang":{"type":"Crafting","rarity":"Common","value":35,"effect":"Beast crafting reagent"},
		"Wolf Claw":{"type":"Crafting","rarity":"Common","value":40,"effect":"Wolf crafting reagent"},
		"Goblin Ear":{"type":"Crafting","rarity":"Common","value":40,"effect":"Goblin crafting reagent"},
		"Orc Tusk":{"type":"Crafting","rarity":"Uncommon","value":90,"effect":"Orc crafting reagent"},
		"Mantis Shell":{"type":"Crafting","rarity":"Uncommon","value":110,"effect":"Mantis crafting reagent"},
		"Skeleton Bone":{"type":"Crafting","rarity":"Common","value":50,"effect":"Undead crafting reagent"},
		"Zombie Heart":{"type":"Crafting","rarity":"Uncommon","value":80,"effect":"Undead crafting reagent"},
		"Golem Core":{"type":"Crafting","rarity":"Rare","value":260,"effect":"Golem crafting core"},
		"Druid Relic":{"type":"Crafting","rarity":"Rare","value":320,"effect":"Dark magic crafting relic"},
		"Dragon Scale":{"type":"Crafting","rarity":"Epic","value":850,"effect":"Endgame dragon crafting reagent"},
		"Apple":{"type":"Consumable","rarity":"Common","value":5,"effect":"Heal 30 HP"},
		"Iron Ore":{"type":"Crafting","rarity":"Common","value":20,"effect":"Basic metal crafting material"},
		"Bone":{"type":"Crafting","rarity":"Common","value":18,"effect":"Bone crafting material"},
		"Rotten Bone":{"type":"Crafting","rarity":"Common","value":22,"effect":"Undead crafting material"},
		"Orc Fang":{"type":"Crafting","rarity":"Uncommon","value":55,"effect":"Orc crafting material"},
		"Sharp Claw":{"type":"Crafting","rarity":"Uncommon","value":60,"effect":"Mantis crafting material"},
		"Stone Fragment":{"type":"Crafting","rarity":"Common","value":25,"effect":"Stone crafting material"},
		"Dark Branch":{"type":"Crafting","rarity":"Rare","value":180,"effect":"Dark magic crafting material"},
		"Novice Sword":{"type":"Weapon","slot":"weapon","rarity":"Common","value":120,"attack":12,"card_slots":0,"refine_cap":15},
		"Iron Longsword":{"type":"Weapon","slot":"weapon","rarity":"Uncommon","value":650,"attack":32,"card_slots":1,"refine_cap":15},
		"Knight Claymore":{"type":"Weapon","slot":"weapon","rarity":"Rare","value":2400,"attack":70,"card_slots":2,"refine_cap":15},
		"War Emperor Blade":{"type":"Weapon","slot":"weapon","rarity":"Legendary","value":15000,"attack":180,"card_slots":3,"refine_cap":15},
		"Arcane Staff":{"type":"Weapon","slot":"weapon","rarity":"Uncommon","value":700,"attack":38,"magic":42,"card_slots":1,"refine_cap":15},
		"Astral Sovereign Staff":{"type":"Weapon","slot":"weapon","rarity":"Legendary","value":16000,"attack":150,"magic":220,"card_slots":3,"refine_cap":15},
		"Hunter Bow":{"type":"Weapon","slot":"weapon","rarity":"Uncommon","value":680,"attack":35,"crit":4,"card_slots":1,"refine_cap":15},
		"Celestial Longbow":{"type":"Weapon","slot":"weapon","rarity":"Legendary","value":15500,"attack":170,"crit":15,"card_slots":3,"refine_cap":15},
		"Shadow Dagger":{"type":"Weapon","slot":"weapon","rarity":"Rare","value":2100,"attack":62,"crit":8,"card_slots":2,"refine_cap":15},
		"Eternal Assassin Blade":{"type":"Weapon","slot":"weapon","rarity":"Legendary","value":17000,"attack":195,"crit":20,"card_slots":3,"refine_cap":15},
		"Holy Mace":{"type":"Weapon","slot":"weapon","rarity":"Uncommon","value":600,"attack":30,"healing":12,"card_slots":1,"refine_cap":15},
		"Heaven Gate Mace":{"type":"Weapon","slot":"weapon","rarity":"Legendary","value":15000,"attack":145,"healing":80,"card_slots":3,"refine_cap":15},
		"Merchant Hammer":{"type":"Weapon","slot":"weapon","rarity":"Uncommon","value":620,"attack":34,"defense":8,"card_slots":1,"refine_cap":15},
		"Arsenal Overlord Hammer":{"type":"Weapon","slot":"weapon","rarity":"Legendary","value":16500,"attack":165,"defense":45,"card_slots":3,"refine_cap":15},
		"Novice Shield":{"type":"Armor","slot":"shield","rarity":"Common","value":100,"defense":10,"card_slots":0,"refine_cap":15},
		"Guardian Shield":{"type":"Armor","slot":"shield","rarity":"Rare","value":2400,"defense":55,"hp":180,"card_slots":2,"refine_cap":15},
		"Aegis of Honour":{"type":"Armor","slot":"shield","rarity":"Legendary","value":17000,"defense":130,"hp":650,"card_slots":3,"refine_cap":15},
		"Novice Cap":{"type":"Armor","slot":"head_upper","rarity":"Common","value":80,"defense":3,"card_slots":1,"refine_cap":15},
		"Iron Helm":{"type":"Armor","slot":"head_upper","rarity":"Uncommon","value":500,"defense":16,"card_slots":1,"refine_cap":15},
		"Crown of Valor":{"type":"Armor","slot":"head_upper","rarity":"Rare","value":2800,"defense":35,"hp":180,"card_slots":2,"refine_cap":15},
		"Arcane Circlet":{"type":"Armor","slot":"head_upper","rarity":"Epic","value":5200,"defense":28,"magic":65,"sp":80,"card_slots":2,"refine_cap":15},
		"Celestial Crown":{"type":"Armor","slot":"head_upper","rarity":"Legendary","value":18000,"defense":70,"hp":400,"magic":90,"card_slots":4,"refine_cap":15,"effect":"Maximum 4 headgear card slots"},
		"Shadow Hood":{"type":"Armor","slot":"head_upper","rarity":"Epic","value":6500,"defense":42,"evasion":12,"crit":5,"card_slots":3,"refine_cap":15},
		"Saint Halo":{"type":"Armor","slot":"head_upper","rarity":"Legendary","value":17500,"defense":60,"healing":55,"sp":160,"card_slots":4,"refine_cap":15,"effect":"Maximum 4 headgear card slots"},
		"Forge Master Visor":{"type":"Armor","slot":"head_upper","rarity":"Legendary","value":17500,"defense":75,"carry":50,"card_slots":4,"refine_cap":15,"effect":"Maximum 4 headgear card slots"},
		"Silver Circlet":{"type":"Armor","slot":"head_middle","rarity":"Uncommon","value":700,"defense":8,"card_slots":1,"refine_cap":15},
		"Ruby Visor":{"type":"Armor","slot":"head_middle","rarity":"Rare","value":2600,"defense":18,"fire_percent":5.0,"card_slots":2,"refine_cap":15},
		"Shadow Mask":{"type":"Armor","slot":"head_middle","rarity":"Rare","value":2800,"defense":15,"evasion":6,"card_slots":2,"refine_cap":15},
		"Dragon Eye Lens":{"type":"Armor","slot":"head_middle","rarity":"Epic","value":6000,"defense":25,"crit":8,"boss_damage_percent":5.0,"card_slots":3,"refine_cap":15},
		"Novice Scarf":{"type":"Armor","slot":"head_lower","rarity":"Common","value":60,"defense":2,"card_slots":0,"refine_cap":15},
		"Wolf Fang Scarf":{"type":"Armor","slot":"head_lower","rarity":"Uncommon","value":500,"defense":7,"move_percent":3.0,"card_slots":1,"refine_cap":15},
		"Dragon Breath Scarf":{"type":"Armor","slot":"head_lower","rarity":"Epic","value":4500,"defense":18,"hp":160,"fire_percent":8.0,"card_slots":2,"refine_cap":15},
		"Novice Armor":{"type":"Armor","slot":"armor","rarity":"Common","value":120,"defense":8,"card_slots":0,"refine_cap":15},
		"Iron Plate":{"type":"Armor","slot":"armor","rarity":"Uncommon","value":700,"defense":28,"card_slots":1,"refine_cap":15},
		"Dragon Scale Armor":{"type":"Armor","slot":"armor","rarity":"Epic","value":6000,"defense":95,"card_slots":2,"refine_cap":15,"effect":"High dragon resistance"},
		"War Emperor Armor":{"type":"Armor","slot":"armor","rarity":"Legendary","value":18000,"defense":180,"hp":500,"card_slots":3,"refine_cap":15},
		"Ranger Mantle":{"type":"Armor","slot":"armor","rarity":"Rare","value":2600,"defense":48,"crit":6,"card_slots":2,"refine_cap":15},
		"Shadow Cloak":{"type":"Armor","slot":"armor","rarity":"Rare","value":2800,"defense":44,"evasion":8,"card_slots":2,"refine_cap":15},
		"Saint Vestment":{"type":"Armor","slot":"armor","rarity":"Epic","value":5000,"defense":72,"healing":30,"card_slots":2,"refine_cap":15},
		"Forge Master Coat":{"type":"Armor","slot":"armor","rarity":"Epic","value":5200,"defense":85,"carry":30,"card_slots":2,"refine_cap":15},
		"Heroic Cloak":{"type":"Armor","slot":"garment","rarity":"Rare","value":3000,"defense":32,"hp":220,"card_slots":2,"refine_cap":15},
		"Celestial Wing Mantle":{"type":"Armor","slot":"garment","rarity":"Legendary","value":16000,"defense":75,"move_percent":8.0,"hp":450,"card_slots":3,"refine_cap":15},
		"Novice Shoes":{"type":"Armor","slot":"shoes","rarity":"Common","value":90,"defense":5,"card_slots":0,"refine_cap":15},
		"Combat Boots":{"type":"Armor","slot":"shoes","rarity":"Uncommon","value":650,"defense":18,"hp":100,"move_percent":4.0,"card_slots":1,"refine_cap":15},
		"Celestial Greaves":{"type":"Armor","slot":"shoes","rarity":"Legendary","value":15000,"defense":55,"hp":300,"move_percent":10.0,"card_slots":3,"refine_cap":15},
		"Ruby Ring":{"type":"Accessory","slot":"accessory_1","rarity":"Rare","value":1500,"hp":180,"fire_percent":3.0,"card_slots":1,"refine_cap":15,"effect":"+3% fire damage"},
		"Sapphire Ring":{"type":"Accessory","slot":"accessory_1","rarity":"Rare","value":1500,"sp":120,"ice_resist_percent":3.0,"card_slots":1,"refine_cap":15,"effect":"+3% ice resistance"},
		"Emerald Brooch":{"type":"Accessory","slot":"accessory_1","rarity":"Rare","value":1500,"crit":5,"wind_percent":3.0,"card_slots":1,"refine_cap":15,"effect":"+3% wind damage"},
		"Amethyst Charm":{"type":"Accessory","slot":"accessory_2","rarity":"Epic","value":2800,"magic":30,"dark_percent":4.0,"card_slots":2,"refine_cap":15,"effect":"+4% dark damage"},
		"Golden Crown":{"type":"Accessory","slot":"accessory_2","rarity":"Legendary","value":9000,"hp":500,"defense":25,"all_rewards_percent":5.0,"card_slots":2,"refine_cap":15,"effect":"+5% all rewards"},
		"MVP Treasure Chest":{"type":"Chest","rarity":"MVP","value":5000,"effect":"Contains premium boss loot"},
		"Boss Soul Shard":{"type":"Crafting","rarity":"MVP","value":2500,"effect":"MVP equipment crafting"},
		"Ancient Dragon Heart":{"type":"Crafting","rarity":"MVP","value":4500,"effect":"Legendary crafting core"},
		"Moon Crystal":{"type":"Crafting","rarity":"MVP","value":3800,"effect":"Endgame enchantment material"},
		"Thanatos Fragment":{"type":"Crafting","rarity":"MVP","value":5000,"effect":"Ultimate weapon material"},
		"Abyssal Relic":{"type":"Crafting","rarity":"MVP","value":7500,"effect":"Mythic equipment material"},
		"MVP Bounty Token":{"type":"Currency","rarity":"MVP","value":1000,"effect":"Exchange for boss rewards"},
		"Teleport Scroll":{"type":"Utility","rarity":"Common","value":100,"effect":"Return to safe city"},
		"Butterfly Wing":{"type":"Utility","rarity":"Common","value":80,"effect":"Return to last safe city"},
		"Magnifier":{"type":"Utility","rarity":"Common","value":40,"effect":"Identify equipment"}
	}
